#undef align_as
#undef align_ptr
#undef ALIGNOF
#undef array_cat
#undef array_free
#undef array_init
#undef array_reserve
#undef array_resize
#undef AT
#undef buffer_free
#undef buffer_init
#undef buffer_reserve
#undef buffer_resize
#undef CAT
#undef CATD
#undef CEILDIV
#undef comm_allreduce
#undef comm_dot
#undef comm_dup
#undef comm_gbl_id
#undef comm_gbl_np
#undef comm_iallreduce
#undef comm_init_check
#undef comm_reduce_sint
#undef comm_reduce_slong
#undef comm_scan
#undef comm_split
#undef COUNT_DIGIT_01
#undef COUNT_DIGIT_02
#undef COUNT_DIGIT_04
#undef COUNT_DIGIT_08
#undef COUNT_DIGIT_16
#undef COUNT_DIGIT_32
#undef COUNT_DIGIT_64
#undef COUNT_SIZE
#undef crystal_free
#undef crystal_init
#undef crystal_router
#undef DATA
#undef DEF_FUNS
#undef DEFINE_REDUCE
#undef diagnostic
#undef die
#undef DIGIT_BITS
#undef DIGIT_MASK
#undef DIGIT_VALUES
#undef DIGITS
#undef eval_out_pt
#undef eval_src_pt
#undef fail
#undef fill_hash
#undef findpts
#undef findpts_2
#undef findpts_3
#undef findpts_data
#undef findpts_dummy_ms_data
#undef findpts_el
#undef findpts_el_2
#undef findpts_el_3
#undef findpts_el_data
#undef findpts_el_eval
#undef findpts_el_eval_2
#undef findpts_el_eval_3
#undef findpts_el_free
#undef findpts_el_free_2
#undef findpts_el_free_3
#undef findpts_el_points
#undef findpts_el_pt
#undef findpts_el_setup
#undef findpts_el_setup_2
#undef findpts_el_setup_3
#undef findpts_el_start
#undef findpts_eval
#undef findpts_eval_2
#undef findpts_eval_3
#undef findpts_free
#undef findpts_free_2
#undef findpts_free_3
#undef findpts_local
#undef findpts_local_2
#undef findpts_local_3
#undef findpts_local_data
#undef findpts_local_eval
#undef findpts_local_eval_2
#undef findpts_local_eval_3
#undef findpts_local_free
#undef findpts_local_free_2
#undef findpts_local_free_3
#undef findpts_local_setup
#undef findpts_local_setup_2
#undef findpts_local_setup_3
#undef findpts_setup
#undef findpts_setup_2
#undef findpts_setup_3
#undef findptsms
#undef findptsms_2
#undef findptsms_3
#undef findptsms_eval
#undef findptsms_eval_2
#undef findptsms_eval_3
#undef findptsms_free
#undef findptsms_free_2
#undef findptsms_free_3
#undef findptsms_local
#undef findptsms_local_2
#undef findptsms_local_3
#undef findptsms_local_eval
#undef findptsms_local_eval_2
#undef findptsms_local_eval_3
#undef findptsms_local_free
#undef findptsms_local_free_2
#undef findptsms_local_free_3
#undef findptsms_local_setup
#undef findptsms_local_setup_2
#undef findptsms_local_setup_3
#undef findptsms_setup
#undef findptsms_setup_2
#undef findptsms_setup_3
#undef FOR_LOOP
#undef free
#undef gauss_nodes
#undef gauss_quad
#undef GLL_LAG_FIX_MAX
#undef gll_lag_setup
#undef gll_lag_size
#undef gs
#undef GS_C99_H
#undef GS_COMM_H
#undef GS_CRYSTAL_H
#undef GS_DEFINE_DOM_SIZES
#undef GS_DEFINE_IDENTITIES
#undef GS_DEFINE_MONOID_ID
#undef GS_DEFS_H
#undef GS_DO_add
#undef GS_DO_bpr
#undef GS_DO_max
#undef GS_DO_min
#undef GS_DO_mul
#undef GS_DOM_SIZE_ITEM
#undef GS_FAIL_H
#undef GS_FINDPTS_EL_H
#undef GS_FINDPTS_LOCAL_H
#undef GS_FINDPTSMS_H
#undef GS_FOR_EACH_DOMAIN
#undef GS_FOR_EACH_OP
#undef gs_free
#undef gs_gather
#undef gs_gather_array
#undef gs_gather_many
#undef gs_gather_vec
#undef gs_gather_vec_to_many
#undef GS_GSLIB_H
#undef GS_H
#undef gs_hf2c
#undef gs_init
#undef gs_init_array
#undef gs_init_many
#undef gs_init_vec
#undef GS_LOB_BND_H
#undef GS_LOCAL_H
#undef gs_many
#undef GS_MEM_H
#undef GS_NAME_H
#undef GS_OBBOX_H
#undef GS_POLY_H
#undef GS_SARRAY_SORT_H
#undef GS_SARRAY_TRANSFER_H
#undef gs_scatter
#undef gs_scatter_many
#undef gs_scatter_many_to_vec
#undef gs_scatter_vec
#undef gs_scatter_vec_to_many
#undef gs_setup
#undef gs_sint
#undef gs_slong
#undef GS_SORT_H
#undef GS_TENSOR_H
#undef GS_TOKEN_PASTE
#undef GS_TOKEN_PASTE_
#undef GS_TYPES_H
#undef gs_unique
#undef gs_vec
#undef gs_wait
#undef GSLIB_FPREFIX
#undef GSLIB_PREFIX
#undef GSLIB_RELEASE_VERSION
#undef GSLIB_UNDERSCORE
#undef GSLIB_USE_GLOBAL_LONG_LONG
#undef GSLIB_USE_MPI
#undef GSLIB_USE_NAIVE_BLAS
#undef hash_bb
#undef hash_build
#undef hash_count
#undef hash_data
#undef hash_free
#undef hash_index
#undef hash_opt_size
#undef hash_range
#undef hash_setfac
#undef heap_sortv
#undef iabs
#undef iabsl
#undef igs
#undef igs_many
#undef igs_vec
#undef INC_PTR
#undef INDEX_PTR
#undef inline
#undef ITEM
#undef lagrange_setup
#undef lagrange_size
#undef LIST
#undef lob_bnd_1
#undef lob_bnd_2
#undef lob_bnd_3
#undef lob_bnd_lin_1
#undef lob_bnd_lin_2
#undef lob_bnd_lin_3
#undef lob_bnd_setup
#undef lobatto_nodes
#undef lobatto_quad
#undef local_hash_data
#undef map_points_to_els
#undef MERGE_2
#undef MERGE_3
#undef merge_copy_perm
#undef MERGE_SORT
#undef merge_sortp
#undef merge_sortp0
#undef merge_sortv
#undef null_array
#undef null_buffer
#undef obbox
#undef obbox_calc
#undef obbox_calc_2
#undef obbox_calc_3
#undef obbox_test
#undef out_pt
#undef pw_data_nmsg
#undef pw_data_size
#undef radix_count
#undef radix_offsets
#undef radix_passp_b
#undef radix_passp_be
#undef radix_passp_e
#undef radix_passp_m
#undef radix_passp0_b
#undef radix_passp0_be
#undef radix_passv
#undef radix_sortp
#undef radix_sortv
#undef radix_zeros
#undef restrict
#undef sarray_permute
#undef sarray_permute_
#undef sarray_permute_buf
#undef sarray_permute_buf_
#undef sarray_sort
#undef sarray_sort_2
#undef sarray_sort_3
#undef sarray_sort_4
#undef sarray_sort_field
#undef sarray_transfer
#undef sarray_transfer_
#undef sarray_transfer_ext
#undef sarray_transfer_ext_
#undef sarray_transfer_many
#undef set_local_mask
#undef setup_fev_aux
#undef setupms_aux
#undef SETVAL
#undef sint
#undef slong
#undef sort_data
#undef sortp
#undef sortp_double
#undef sortp_float
#undef sortp_long
#undef sortp_ui
#undef sortp_ul
#undef sortp_ull
#undef sortv
#undef sortv_double
#undef sortv_float
#undef sortv_long
#undef sortv_ui
#undef sortv_ul
#undef sortv_ull
#undef src_pt
#undef STATIC_DIGIT_BUCKETS
#undef table_from_hash
#undef tcalloc
#undef tmalloc
#undef trealloc
#undef uint
#undef ulong
#undef VAL
#undef VALUE_BITS
#undef VDEF_FUNS
#undef vdiagnostic
#undef vfail