# Copyright (c) 2010-2025, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

# DESCRIPTION:
###############################################################################
# General GitLab pipelines configurations for supercomputers and Linux clusters
# at Lawrence Livermore National Laboratory (LLNL).
# This entire pipeline is LLNL-specific
#
# Important note: This file is a template provided by llnl/radiuss-shared-ci.
# Remains to set variable values, change the reference to the radiuss-shared-ci
# repo, opt-in and out optional features. The project can then extend it with
# additional stages.
#
# In addition, each project should copy over and complete:
# - .gitlab/custom-variables.yml
# - .gitlab/custom-jobs.yml
# - .gitlab/subscribed-pipelines.yml
#
# The jobs should be specified in a file local to the project,
# - .gitlab/jobs/${CI_MACHINE}.yml
# or generated (see LLNL/Umpire for an example).
###############################################################################
#   MAP OF GITLAB CI
#######################
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File dependencies: direct, through jobs, through variables
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# .gitlab-ci.yml
#  ├── <radiuss-shared-ci>/templates/base-pipeline/template.yml  [component]
#  │    ├── .machine-check        [job]
#  │    ├── .build-and-test       [job]
#  │    └── .dane/.matrix/.tioga  [machine selector jobs]
#  ├── .build-and-test  [job, from base-pipeline component above]
#  │    ├── .gitlab/custom-variables.yml
#  │    │    └── JOB_CMD              [var]
#  │    │         └── tests/gitlab/build_and_test            [script]
#  │    │              └── tests/gitlab/get_mfem_uberenv     [script]
#  │    ├── .gitlab/custom-jobs.yml
#  │    │    ├── .custom_job          [job]
#  │    │    ├── .reproducer_vars     [job]
#  │    │    ├── .report_job_success  [job]
#  │    │    │    └── .gitlab/scripts/report_build_and_test    [script]
#  │    │    │         ├── .gitlab/scripts/safe_create_rundir  [script]
#  │    │    │         └── .gitlab/scripts/git_try_to_push     [script]
#  │    │    └── .report_job_failure  [job]
#  │    │         └── .gitlab/scripts/report_build_and_test    [script]
#  │    │              ├── .gitlab/scripts/safe_create_rundir  [script]
#  │    │              └── .gitlab/scripts/git_try_to_push     [script]
#  │    ├── <radiuss-shared-ci>/templates/matrix-pipeline/template.yml  [conditional]
#  │    │    ├── .on_matrix               [job]
#  │    │    ├── .matrix_reproducer_init  [job]
#  │    │    ├── .matrix_reproducer_vars  [job]
#  │    │    ├── .matrix_reproducer_job   [job]
#  │    │    ├── .matrix_job_command      [job]
#  │    │    └── .job_on_matrix           [job]
#  │    ├── <radiuss-shared-ci>/templates/dane-pipeline/template.yml  [conditional]
#  │    │    ├── .on_dane               [job]
#  │    │    ├── .dane_reproducer_init  [job]
#  │    │    ├── .dane_reproducer_vars  [job]
#  │    │    ├── .dane_reproducer_job   [job]
#  │    │    ├── .dane_job_command      [job]
#  │    │    ├── .job_on_dane           [job]
#  │    │    ├── allocate_resources     [job]
#  │    │    └── release_resources      [job]
#  │    ├── <radiuss-shared-ci>/templates/tioga-pipeline/template.yml  [conditional]
#  │    │    ├── .on_tioga               [job]
#  │    │    ├── .tioga_reproducer_init  [job]
#  │    │    ├── .tioga_reproducer_vars  [job]
#  │    │    ├── .tioga_reproducer_job   [job]
#  │    │    ├── .tioga_job_command      [job]
#  │    │    ├── .job_on_tioga           [job]
#  │    │    ├── allocate_resources      [job]
#  │    │    └── release_resources       [job]
#  │    ├── <artifact>/matrix-jobs.yml  [conditional, from 'generate-job-lists']
#  │    │    ├── .gitlab/jobs/matrix.yml
#  │    │    │    ├── .matrix_reproducer_vars      [job]
#  │    │    │    ├── setup                        [job]
#  │    │    │    │    └── ./tests/gitlab/build_and_test_setup  [script]
#  │    │    │    ├── opt_mpi_cuda_gcc             [job]
#  │    │    │    └── opt_mpi_cuda_hypre_cuda_gcc  [job]
#  │    │    └── .gitlab/jobs/matrix-reports.yml  [used conditionally]
#  │    │         ├── report_job_success
#  │    │         └── report_job_failure
#  │    ├── <artifact>/dane-jobs.yml    [conditional, from 'generate-job-lists']
#  │    │    ├── .gitlab/jobs/dane.yml
#  │    │    │    ├── .dane_reproducer_vars    [job]
#  │    │    │    ├── setup                    [job]
#  │    │    │    │    └── ./tests/gitlab/build_and_test_setup  [script]
#  │    │    │    ├── debug_ser_gcc_10         [job]
#  │    │    │    ├── debug_par_gcc_10         [job]
#  │    │    │    ├── opt_ser_gcc_10           [job]
#  │    │    │    ├── opt_par_gcc_10           [job]
#  │    │    │    ├── opt_par_gcc_10_sundials  [job]
#  │    │    │    ├── opt_par_gcc_10_petsc     [job]
#  │    │    │    └── opt_par_gcc_10_pumi      [job]
#  │    │    └── .gitlab/jobs/dane-reports.yml    [used conditionally]
#  │    │         ├── report_job_success
#  │    │         └── report_job_failure
#  │    └── <artifact>/tioga-jobs.yml   [conditional, from 'generate-job-lists']
#  │         ├── .gitlab/jobs/tioga.yml
#  │         │    ├── .tioga_reproducer_vars  [job]
#  │         │    ├── setup                   [job]
#  │         │    │    └── ./tests/gitlab/build_and_test_setup  [script]
#  │         │    └── cce_16_0_1              [job]
#  │         └── .gitlab/jobs/tioga-reports.yml   [used conditionally]
#  │              ├── report_job_success
#  │              └── report_job_failure
#  └── .gitlab/subscribed-pipelines.yml
#       ├── generate-job-lists     [job]
#       ├── dane-up-check          [job]
#       ├── dane-build-and-test    [job]
#       ├── dane-baseline          [job]
#       │    └── .gitlab/dane-baseline.yml
#       │         ├── .on_dane                       [job]
#       │         ├── baselinecheck_mfem_intel_dane  [job]
#       │         │    └── .gitlab/scripts/baseline            [script]
#       │         ├── cleanup                        [job]
#       │         ├── report_baseline                [job]
#       │         │    ├── .gitlab/scripts/safe_create_rundir  [script]
#       │         │    └── .gitlab/scripts/git_try_to_push     [script]
#       │         ├── baselinepublish_mfem_dane      [job]
#       │         │    └── .gitlab/scripts/rebaseline          [script]
#       │         ├── .gitlab/custom-variables.yml
#       │         └── .gitlab/configs/setup-baseline.yml
#       │              └── setup_baseline            [job]
#       ├── tioga-up-check         [job]
#       ├── tioga-build-and-test   [job]
#       ├── matrix-up-check        [job]
#       └── matrix-build-and-test  [job]
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File tree hierarchy with file contents highlights
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# In addition to the files in the MFEM repo, the Gitlab CI uses files from the
# radiuss/radiuss-shared-ci project, see below, after the <mfem-root> tree.
#
# <mfem root>
#  ├── .gitlab-ci.yml  [this file]
#  │    ├── <included files>
#  │    │    ├── <component>  [base-pipeline, by parent pipeline]
#  │    │    │    ├── project:   'radiuss/radiuss-shared-ci'
#  │    │    │    ├── ref:       '2026.6.0'
#  │    │    │    ├── component: 'base-pipeline'
#  │    │    │    └── provides:  .machine-check, .build-and-test, .dane/.matrix/.tioga
#  │    │    ├── .gitlab/subscribed-pipelines.yml
#  │    │    ├── .gitlab/custom-variables.yml  [by parent pipeline]
#  │    │    ├── .gitlab/custom-jobs.yml  [by ".build-and-test"]
#  │    │    ├── <artifact>  [by ".build-and-test"]
#  │    │    │    ├── artifact: '${CI_MACHINE}-jobs.yml'
#  │    │    │    └── job:      'generate-job-lists'
#  │    │    └── <component>  [${CI_MACHINE}-pipeline, by ".build-and-test"]
#  │    │         ├── project:   'radiuss/radiuss-shared-ci'
#  │    │         ├── ref:       '2026.6.0'
#  │    │         └── component: '${CI_MACHINE}-pipeline'
#  │    └── <defined variables>
#  │         ├── CUSTOM_CI_BUILDS_DIR
#  │         ├── USER_CI_TOP_DIR
#  │         ├── SHARED_REPOS_DIR
#  │         ├── AUTOTEST_ROOT
#  │         ├── MFEM_DATA_DIR
#  │         ├── AUTOTEST
#  │         ├── AUTOTEST_COMMIT
#  │         ├── REBASELINE
#  │         ├── GITHUB_PROJECT_NAME
#  │         └── GITHUB_PROJECT_ORG
#  ├── .gitlab
#  │    ├── configs
#  │    │    └── setup-baseline.yml
#  │    │         ├── <jobs>
#  │    │         │    └── setup_baseline
#  │    │         └── <used variables>
#  │    │              ├── MACHINE_NAME
#  │    │              ├── REBASELINE
#  │    │              ├── AUTOTEST
#  │    │              ├── AUTOTEST_COMMIT
#  │    │              ├── BUILD_ROOT
#  │    │              ├── TPLS_REPO
#  │    │              ├── TESTS_REPO
#  │    │              ├── AUTOTEST_ROOT
#  │    │              └── AUTOTEST_REPO
#  │    ├── jobs
#  │    │    ├── matrix-reports.yml
#  │    │    │    ├── <jobs>
#  │    │    │    │    ├── report_job_success
#  │    │    │    │    └── report_job_failure
#  │    │    │    └── <used jobs>
#  │    │    │         ├── .on_matrix
#  │    │    │         ├── .report_job_success
#  │    │    │         └── .report_job_failure
#  │    │    ├── matrix.yml
#  │    │    │    ├── <jobs>
#  │    │    │    │    ├── .matrix_reproducer_vars
#  │    │    │    │    ├── setup
#  │    │    │    │    ├── opt_mpi_cuda_gcc
#  │    │    │    │    └── opt_mpi_cuda_hypre_cuda_gcc
#  │    │    │    ├── <used jobs>
#  │    │    │    │    ├── .reproducer_vars
#  │    │    │    │    ├── .on_matrix
#  │    │    │    │    └── .job_on_matrix
#  │    │    │    ├── <included and used files>
#  │    │    │    │    └── tests/gitlab/build_and_test_setup  [by "setup"]
#  │    │    │    └── <defined variables>
#  │    │    │         └── SPEC
#  │    │    ├── dane-reports.yml
#  │    │    │    ├── <jobs>
#  │    │    │    │    ├── report_job_success
#  │    │    │    │    └── report_job_failure
#  │    │    │    └── <used jobs>
#  │    │    │         ├── .on_dane
#  │    │    │         ├── .report_job_success
#  │    │    │         └── .report_job_failure
#  │    │    ├── dane.yml
#  │    │    │    ├── <jobs>
#  │    │    │    │    ├── .dane_reproducer_vars
#  │    │    │    │    ├── setup
#  │    │    │    │    ├── debug_ser_gcc_10
#  │    │    │    │    ├── debug_par_gcc_10
#  │    │    │    │    ├── opt_ser_gcc_10
#  │    │    │    │    ├── opt_par_gcc_10
#  │    │    │    │    ├── opt_par_gcc_10_sundials
#  │    │    │    │    ├── opt_par_gcc_10_petsc
#  │    │    │    │    └── opt_par_gcc_10_pumi
#  │    │    │    ├── <used jobs>
#  │    │    │    │    ├── .reproducer_vars
#  │    │    │    │    ├── .on_dane
#  │    │    │    │    └── .job_on_dane
#  │    │    │    ├── <included and used files>
#  │    │    │    │    └── tests/gitlab/build_and_test_setup  [by "setup"]
#  │    │    │    └── <defined variables>
#  │    │    │         ├── SPEC
#  │    │    │         └── THREADS
#  │    │    ├── tioga-reports.yml
#  │    │    │    ├── <jobs>
#  │    │    │    │    ├── report_job_success
#  │    │    │    │    └── report_job_failure
#  │    │    │    └── <used jobs>
#  │    │    │         ├── .on_tioga
#  │    │    │         ├── .report_job_success
#  │    │    │         └── .report_job_failure
#  │    │    └── tioga.yml
#  │    │         ├── <jobs>
#  │    │         │    ├── .tioga_reproducer_vars
#  │    │         │    ├── setup
#  │    │         │    └── opt_mpi_rocm_hypre_rocm
#  │    │         ├── <used jobs>
#  │    │         │    ├── .reproducer_vars
#  │    │         │    ├── .on_tioga
#  │    │         │    └── .job_on_tioga
#  │    │         ├── <included and used files>
#  │    │         │    └── tests/gitlab/build_and_test_setup  [by "setup"]
#  │    │         └── <defined variables>
#  │    │              ├── SPEC
#  │    │              └── THREADS
#  │    ├── scripts
#  │    │    ├── baseline
#  │    │    │    └── <used variables>
#  │    │    │         ├── BASELINE_TEST
#  │    │    │         ├── SYS_TYPE
#  │    │    │         ├── MACHINE_NAME
#  │    │    │         ├── CI_PROJECT_DIR
#  │    │    │         ├── ARTIFACTS_DIR
#  │    │    │         ├── BUILD_ROOT
#  │    │    │         └── TPLS_DIR
#  │    │    ├── git_try_to_push
#  │    │    ├── rebaseline
#  │    │    │    └── <used variables>
#  │    │    │         ├── CI_PROJECT_DIR
#  │    │    │         ├── ARTIFACTS_DIR
#  │    │    │         ├── SYS_TYPE
#  │    │    │         ├── BUILD_ROOT
#  │    │    │         ├── MACHINE_NAME
#  │    │    │         └── CI_PIPELINE_ID
#  │    │    ├── report_build_and_test
#  │    │    │    ├── <used files>
#  │    │    │    │    ├── .gitlab/scripts/safe_create_rundir
#  │    │    │    │    └── .gitlab/scripts/git_try_to_push
#  │    │    │    └── <used variables>
#  │    │    │         ├── AUTOTEST_ROOT
#  │    │    │         ├── CI_COMMIT_REF_SLUG
#  │    │    │         ├── CI_PROJECT_DIR
#  │    │    │         ├── CI_PIPELINE_URL
#  │    │    │         ├── AUTOTEST_COMMIT
#  │    │    │         └── CI_MACHINE
#  │    │    └── safe_create_rundir
#  │    ├── custom-jobs.yml
#  │    │    ├── <jobs>
#  │    │    │    ├── .custom_job
#  │    │    │    ├── .reproducer_vars
#  │    │    │    ├── .report_job_success
#  │    │    │    └── .report_job_failure
#  │    │    └── <used variables>
#  │    │         ├── SPEC
#  │    │         ├── BUILD_ROOT
#  │    │         └── ...
#  │    ├── custom-variables.yml
#  │    │    ├── <used files>
#  │    │    │    └── tests/gitlab/build_and_test  [in JOB_CMD]
#  │    │    └── <defined variables>
#  │    │         ├── JOB_CMD
#  │    │         ├── BUILD_ROOT
#  │    │         ├── ALLOC_NAME
#  │    │         ├── TPLS_REPO
#  │    │         ├── TESTS_REPO
#  │    │         ├── AUTOTEST_REPO
#  │    │         ├── MFEM_DATA_REPO
#  │    │         ├── ARTIFACTS_DIR: artifacts
#  │    │         ├── SLURM_OVERLAP: 1
#  │    │         ├── DANE_SHARED_ALLOC
#  │    │         ├── DANE_JOB_ALLOC
#  │    │         ├── TIOGA_SHARED_ALLOC
#  │    │         ├── TIOGA_JOB_ALLOC
#  │    │         └── MATRIX_JOB_ALLOC
#  │    ├── dane-baseline.yml
#  │    │    ├── <jobs>
#  │    │    │    ├── .on_dane
#  │    │    │    ├── baselinecheck_mfem_intel_dane
#  │    │    │    ├── cleanup
#  │    │    │    ├── report_baseline
#  │    │    │    └── baselinepublish_mfem_dane
#  │    │    ├── <included and used files>
#  │    │    │    ├── .gitlab/custom-variables.yml
#  │    │    │    ├── .gitlab/configs/setup-baseline.yml
#  │    │    │    ├── .gitlab/scripts/rebaseline
#  │    │    │    ├── .gitlab/scripts/baseline
#  │    │    │    └── .gitlab/scripts/git_try_to_push
#  │    │    ├── <defined variables>
#  │    │    │    ├── BASELINE_TEST: baseline
#  │    │    │    ├── MACHINE_NAME: dane
#  │    │    │    ├── TPLS_DIR
#  │    │    │    └── export MFEM_TEST_NP
#  │    │    └── <used variables>
#  │    │         ├── ON_DANE
#  │    │         ├── AUTOTEST       [defined by .gitlab-ci.yml]
#  │    │         ├── BUILD_ROOT     [defined by custom-variables.yml]
#  │    │         ├── TPLS_DIR       [defined by this file]
#  │    │         ├── ARTIFACTS_DIR  [defined by custom-variables.yml]
#  │    │         ├── MACHINE_NAME   [defined by this file]
#  │    │         ├── AUTOTEST_COMMIT  [defined by .gitlab-ci.yml]
#  │    │         ├── AUTOTEST_ROOT  [defined by .gitlab-ci.yml]
#  │    │         ├── BASELINE_TEST  [defined by this file]
#  │    │         └── REBASELINE     [defined by .gitlab-ci.yml]
#  │    └── subscribed-pipelines.yml
#  │         ├── <jobs>
#  │         │    ├── generate-job-lists
#  │         │    ├── dane-up-check
#  │         │    ├── dane-build-and-test
#  │         │    ├── dane-baseline
#  │         │    ├── tioga-up-check
#  │         │    ├── tioga-build-and-test
#  │         │    ├── matrix-up-check
#  │         │    └── matrix-build-and-test
#  │         ├── <used jobs>
#  │         │    ├── .machine-check    [from base-pipeline component]
#  │         │    └── .build-and-test   [from base-pipeline component]
#  │         ├── <included files>
#  │         │    └── .gitlab/dane-baseline.yml  [by "dane-baseline"]
#  │         └── <used variables>
#  │              ├── GITHUB_PROJECT_ORG
#  │              ├── GITHUB_PROJECT_NAME
#  │              ├── AUTOTEST
#  │              ├── AUTOTEST_COMMIT
#  │              └── REBASELINE
#  └── tests
#       ├── gitlab
#       │    ├── build_and_test
#       │    │    ├── <builds and tests a given MFEM spec with uberenv>
#       │    │    ├── <used files>
#       │    │    │    ├── tests/uberenv/uberenv.py        [deps mode, cloned]
#       │    │    │    └── tests/gitlab/get_mfem_uberenv   [deps mode]
#       │    │    └── <used variables>
#       │    │         ├── SYS_TYPE
#       │    │         ├── THREADS      [num. parallel jobs to build MFEM]
#       │    │         ├── MODULE_LIST  [modules to load]
#       │    │         ├── CI_JOB_ID
#       │    │         ├── USE_DEV_SHM
#       │    │         ├── SPACK_DEBUG
#       │    │         ├── DEBUG_MODE
#       │    │         ├── REGISTRY_TOKEN
#       │    │         ├── CI_REGISTRY_USER  (defined by Gitlab)
#       │    │         ├── USER
#       │    │         ├── CI_REGISTRY_IMAGE (defined by Gitlab)
#       │    │         └── CI_JOB_TOKEN      (defined by Gitlab)
#       │    ├── build_and_test_setup
#       │    │    ├── <updates MFEM_DATA_REPO and AUTOTEST_REPO using locks>
#       │    │    └── <used variables>
#       │    │         ├── MFEM_DATA_REPO
#       │    │         ├── SHARED_REPOS_DIR
#       │    │         ├── AUTOTEST_REPO
#       │    │         └── AUTOTEST_ROOT
#       │    └── get_mfem_uberenv
#       │         ├── <github.com/mfem/mfem-uberenv.git -> tests/uberenv>
#       │         └── <defines the uberenv hash to use>
#       └── uberenv  [cloned by tests/gitlab/get_mfem_uberenv]
#            └── uberenv.py
#
# <root of radiuss/radiuss-shared-ci, ref: '2026.6.0'>
#  └── templates
#       ├── base-pipeline/template.yml
#       │    └── <jobs>
#       │         ├── .machine-check
#       │         ├── .build-and-test
#       │         ├── .dane
#       │         ├── .matrix
#       │         └── .tioga
#       ├── matrix-pipeline/template.yml
#       │    ├── <jobs>
#       │    │    ├── .on_matrix
#       │    │    ├── .matrix_reproducer_init
#       │    │    ├── .matrix_reproducer_vars
#       │    │    ├── .matrix_reproducer_job
#       │    │    ├── .matrix_job_command
#       │    │    └── .job_on_matrix
#       │    ├── <used jobs>
#       │    │    └── .custom_job  [from .gitlab/custom-jobs.yml]
#       │    └── <used variables>
#       │         ├── ON_MATRIX
#       │         ├── ADVANCED_JOB
#       │         ├── ALL_TARGETS
#       │         ├── SYS_TYPE
#       │         ├── LLNL_SERVICE_USER
#       │         ├── USER
#       │         ├── GITHUB_PROJECT_NAME
#       │         ├── GITHUB_PROJECT_ORG
#       │         ├── RSCI_MATRIX_JOB_ALLOC
#       │         └── RSCI_JOB_CMD
#       ├── dane-pipeline/template.yml
#       │    ├── <jobs>
#       │    │    ├── .on_dane
#       │    │    ├── .dane_reproducer_init
#       │    │    ├── .dane_reproducer_vars
#       │    │    ├── .dane_reproducer_job
#       │    │    ├── .dane_job_command
#       │    │    ├── .job_on_dane
#       │    │    ├── allocate_resources
#       │    │    └── release_resources
#       │    ├── <used jobs>
#       │    │    └── .custom_job  [from .gitlab/custom-jobs.yml]
#       │    ├── <defined variables>
#       │    │    └── export JOBID
#       │    └── <used variables>
#       │         ├── ON_DANE
#       │         ├── ADVANCED_JOB
#       │         ├── ALL_TARGETS
#       │         ├── SYS_TYPE
#       │         ├── LLNL_SERVICE_USER
#       │         ├── USER
#       │         ├── GITHUB_PROJECT_NAME
#       │         ├── GITHUB_PROJECT_ORG
#       │         ├── RSCI_DANE_JOB_ALLOC
#       │         ├── RSCI_JOB_CMD
#       │         ├── JOBID
#       │         ├── RSCI_ALLOC_NAME
#       │         └── RSCI_DANE_SHARED_ALLOC
#       └── tioga-pipeline/template.yml
#            ├── <jobs>
#            │    ├── .on_tioga
#            │    ├── .tioga_reproducer_init
#            │    ├── .tioga_reproducer_vars
#            │    ├── .tioga_reproducer_job
#            │    ├── .tioga_job_command
#            │    ├── .job_on_tioga
#            │    ├── allocate_resources
#            │    └── release_resources
#            ├── <used jobs>
#            │    └── .custom_job  [from .gitlab/custom-jobs.yml]
#            ├── <defined variables>
#            │    └── PROXY
#            └── <used variables>
#                 ├── ON_TIOGA
#                 ├── ADVANCED_JOB
#                 ├── ALL_TARGETS
#                 ├── SYS_TYPE
#                 ├── LLNL_SERVICE_USER
#                 ├── USER
#                 ├── GITHUB_PROJECT_NAME
#                 ├── GITHUB_PROJECT_ORG
#                 ├── RSCI_TIOGA_JOB_ALLOC
#                 ├── RSCI_JOB_CMD
#                 ├── PROXY
#                 ├── RSCI_ALLOC_NAME
#                 └── RSCI_TIOGA_SHARED_ALLOC

###############################################################################
# We define the following GitLab pipeline variables:
variables:
##### LC GITLAB CONFIGURATION
  CUSTOM_CI_BUILDS_DIR: "/usr/workspace/mfem/gitlab-runner"

##### PROJECT VARIABLES
  USER_CI_TOP_DIR: "${CUSTOM_CI_BUILDS_DIR}/${GITLAB_USER_LOGIN}"
  SHARED_REPOS_DIR: "${USER_CI_TOP_DIR}/repos"
  AUTOTEST_ROOT: "${SHARED_REPOS_DIR}"
  MFEM_DATA_DIR: "${SHARED_REPOS_DIR}/mfem-data"
# AUTOTEST: enable (ON/YES) or disable (any other value) test reporting. See
# also AUTOTEST_COMMIT.
  AUTOTEST: "OFF"
# AUTOTEST_COMMIT: used only when AUTOTEST is set to ON/YES.
# * If AUTOTEST_COMMIT is set to ON/YES, reporting jobs will commit their
#   files to the MFEM/autotest repo.
# * If AUTOTEST_COMMIT is NOT set to ON/YES, reporting jobs will NOT commit
#   their files to the MFEM/autotest repo. Instead they will just show the
#   contents of the report files and remove them.
  AUTOTEST_COMMIT: "ON"
# REBASELINE:
# Defines the default choice for updating the saved baseline results. By default
# the baseline can only be updated from the master branch. This variable offers
# the option to manually ask for rebaselining from another branch if necessary.
  REBASELINE: "OFF"

##### SHARED_CI CONFIGURATION
# Required information about GitHub repository
  GITHUB_PROJECT_NAME: "mfem"
  GITHUB_PROJECT_ORG: "MFEM"
# Override the pattern describing branches that will skip the "draft PR filter
# test". Add protected branches here. See default value in
# utility-draft-pr-filter.
#  ALWAYS_RUN_PATTERN: ""

###############################################################################
##### High level stages
# We organize the build-and-test stage with sub-pipelines. Each sub-pipeline
# corresponds to a test batch on a given machine.
stages:
  - prerequisites
  - build-and-test

###############################################################################
include:
  - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/base-pipeline@2026.6.0
    inputs:
      github_project_name: $GITHUB_PROJECT_NAME
      github_project_org: $GITHUB_PROJECT_ORG
      github_token: $GITHUB_TOKEN
  # [Optional] checks preliminary to running the actual CI test
  #- component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/utility-draft-pr-filter@2026.6.0
  #  inputs:
  #    github_token: $GITHUB_TOKEN
  #    github_project_name: $GITHUB_PROJECT_NAME
  #    github_project_org: $GITHUB_PROJECT_ORG
  #    always_run_pattern: $ALWAYS_RUN_PATTERN
  - local: '.gitlab/custom-variables.yml'
  # pipelines subscribed by the project
  - local: '.gitlab/subscribed-pipelines.yml'
