#!/bin/sh

# Copyright (c) 2010, Lawrence Livermore National Security, LLC. Produced at the
# Lawrence Livermore National Laboratory. LLNL-CODE-443211. All Rights reserved.
# See file COPYRIGHT for details.
#
# This file is part of the MFEM library. For more information and source code
# availability see http://mfem.googlecode.com.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.

# Echo usage information
case $1 in
   -h|-help)
      cat <<EOF

   $0 [-h|-help] {mfem_dir}

   where: {mfem_dir}  is the MFEM source directory [default value: ../mfem]
          -h|-help    prints this usage information and exits

   This script runs several documentation-related tests in mfem_dir.

   Example usage: $0 ../mfem

EOF
      exit
      ;;
esac

# Setup
mfem_dir=$1
if [ "$mfem_dir" = "" ]; then
    mfem_dir="../mfem"
fi
shift
cd $mfem_dir

# Test the documentation of some make targets
make help
make distclean
make config MFEM_USE_MPI=YES
make status

# Test the build of example codes documentation
# cd examples/doc; make distclean; make

# Test the build of the Doxygen documentation
cd doc; make clean; make
