#!/bin/bash

echo "Runs if there was at least one failure on ${MACHINE_NAME}"

cd ${AUTOTEST_ROOT}/autotest && git pull

rundir="${MACHINE_NAME}/$(date +%Y-%m-%d)-gitlab-ci-${CI_COMMIT_REF_SLUG}"
rundir=$(.gitlab/scripts/safe_create_rundir $rundir)

echo "There was an error while running CI on ${MACHINE_NAME}" > ${rundir}/gitlab.err
echo "See the pipeline here -> $CI_PIPELINE_URL" >> ${rundir}/gitlab.err

msg="Gitlab CI log for build-and-test on ${MACHINE_NAME} ($(date +%Y-%m-%d))"

cp ${rundir}/gitlab.err ${rundir}/autotest-email.html

git add ${rundir}
git commit -am "${msg}"
git push origin master
