#!/bin/bash

echo "Can only run if all the ${MACHINE_NAME} jobs passed"

cd ${AUTOTEST_ROOT}/autotest && git pull

rundir="${MACHINE_NAME}/$(date +%Y-%m-%d)-gitlab-ci-${CI_COMMIT_REF_SLUG}"
rundir=$(.gitlab/scripts/safe_create_rundir $rundir)

echo "The ${MACHINE_NAME} jobs were successful" > ${rundir}/gitlab.out
echo "See the pipeline here -> $CI_PIPELINE_URL" >> ${rundir}/gitlab.err

msg="Gitlab CI log for build-and-test on ${MACHINE_NAME} ($(date +%Y-%m-%d))"

git add ${rundir}
git commit -am "${msg}"
git push origin master
