#!/bin/bash

# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

echo "Runs if there was at least one failure on ${MACHINE_NAME}"

cd ${AUTOTEST_ROOT}/autotest && git pull

rundir="${MACHINE_NAME}/$(date +%Y-%m-%d)-gitlab-ci-${CI_COMMIT_REF_SLUG}"
rundir=$(.gitlab/scripts/safe_create_rundir $rundir)

echo "There was an error while running CI on ${MACHINE_NAME}" > ${rundir}/gitlab.err
echo "See the pipeline here -> $CI_PIPELINE_URL" >> ${rundir}/gitlab.err

msg="Gitlab CI log for build-and-test on ${MACHINE_NAME} ($(date +%Y-%m-%d))"

cp ${rundir}/gitlab.err ${rundir}/autotest-email.html

git add ${rundir}
git commit -am "${msg}"
git push origin master
