#!/usr/bin/env bash

# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

set -o errexit
set -o nounset

option=${1:-""}
hostname="$(hostname)"
project_dir="$(pwd)"

build_root=${BUILD_ROOT:-""}
hostconfig=${HOST_CONFIG:-""}
spec=${SPEC:-""}

sys_type=${SYS_TYPE:-""}
py_env_path=${PYTHON_ENVIRONMENT_PATH:-""}
ci_context=${CI:-""}

threads=${THREADS:-""}

# Dependencies
if [[ "${option}" != "--build-only" && "${option}" != "--test-only" ]]
then
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "~~~~~ Building Dependencies"
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

    if [[ -z ${spec} ]]
    then
        echo "SPEC is undefined, aborting..."
        exit 1
    fi

    upstream_opt=""
    if [[ ${CI_COMMIT_BRANCH:-"master"} != "master" && ${sys_type} != "" ]]
    then
        upstream_opt="--upstream=/usr/workspace/mfem/spack-upstream/uberenv_libs"
    fi

    prefix_opt=""

    # Do not run on /dev/shm if only installing dependencies: they will be lost
    # otherwise.
    if [[ -d "/dev/shm" && "${option}" != "--deps-only" ]]
    then
        prefix="/dev/shm/${hostname}/${CI_PIPELINE_ID:-"NONE"}_${RANDOM}"
        mkdir -p ${prefix}
        echo ${spec} > spec.txt
        prefix_opt="--prefix=${prefix}"
    fi

    echo "Fetching uberenv."
    tests/gitlab/get_mfem_uberenv || ( echo "Error fetching Uberenv" && exit 1 );

    echo "Installing dependencies."
    python tests/uberenv/uberenv.py --spec="${spec}" "${upstream_opt}" "${prefix_opt}"

    mkdir -p host-configs
    mv ${project_dir}/hc-*.mk host-configs/
fi

# Host config file
if [[ "${option}" != "--deps-only" ]]
then
  if [[ -z ${hostconfig} ]]
  then
      # If no host config file was provided, we assume it was generated.
      # This means we are looking of a unique one.
      hostconfigs=( $( ls "${project_dir}/host-configs/"hc-*.mk || true ) )
      if [[ ${#hostconfigs[@]} == 1 ]]
      then
          hostconfig_path=${hostconfigs[0]}
          echo "Found host config file: ${hostconfig_path}"
      elif [[ ${#hostconfigs[@]} == 0 ]]
      then
          echo "No result for: ${project_dir}/host-configs/hc-*.mk"
          echo "Spack generated host-config not found."
          exit 1
      else
          echo "More than one result for: ${project_dir}/host-configs/hc-*.mk"
          echo "${hostconfigs[@]}"
          echo "Please specify one with HOST_CONFIG variable"
          exit 1
      fi
  else
      # Using provided host-config file.
      hostconfig_path="${project_dir}/${hostconfig}"
  fi
fi

# Build Directory
if [[ -z ${build_root} ]]
then
    build_root=$(pwd)
fi

# Build (also build when asked for testing, to make sure we test what we want)
if [[ "${option}" != "--deps-only" ]]
then
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "~ Host-config: ${hostconfig_path}"
    echo "~ Project Dir: ${project_dir}"
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "~~~~~ Building MFEM"
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

    cp ${hostconfig_path} ${project_dir}/config/
    ln -sf ${build_root}/data ${project_dir}/../

    make all -j ${threads}
fi

# Test
if [[ "${option}" != "--deps-only" && "${option}" != "--build-only" ]]
then
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    echo "~~~~~ Testing MFEM"
    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

    return_code=0
    make test 2>&1 | tee tests_output.txt || return_code=${?}

    if grep -q "All tests passed." ./tests_output.txt
    then
        echo "SUCCESS: No error during tests" && exit 0
    else
        echo "ERROR: failure(s) while running MFEM tests" && exit 1
    fi
fi
