#!/bin/sh

# Copyright (c) 2010, Lawrence Livermore National Security, LLC. Produced at the
# Lawrence Livermore National Laboratory. LLNL-CODE-443211. All Rights reserved.
# See file COPYRIGHT for details.
#
# This file is part of the MFEM library. For more information and source code
# availability see http://mfem.googlecode.com.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.

build_np=${MFEM_TEST_NP:-4}

# Echo usage information
case $1 in
   -h|-help)
      cat <<EOF

   $0 [-h|-help] {mfem_dir} {glvis_dir} {tpls_dir}

   where: {mfem_dir}  is the MFEM source directory [default value: ../mfem]
          {glvis_dir} is the GLVis source directory [default value: ../glvis]
          {tpls_dir}  is the third party libraries directory (hypre, metis, etc)
                      [default value: ../tpls]
          -h|-help    prints this usage information and exits

   Check the building of MFEM, its examples, miniapps and GLVis with the support
   enabled for third party libraries in MFEM (suitesparse, superlu, etc).

   Optional environment variables used by this script:
     MFEM_TEST_NP - number of processors to use for building, default: 4

   Example usage: $0 ../.. ../../../glvis ../../../tpls

EOF
      exit
      ;;
esac

# Setup
mfem_dir=$1
if [ "$mfem_dir" = "" ]; then
    mfem_dir="../.."
fi
cd $mfem_dir
mfem_dir=`pwd`
shift

glvis_dir=$1
if [ "$glvis_dir" = "" ]; then
    glvis_dir="../../../glvis"
fi
cd $glvis_dir
glvis_dir=`pwd`
shift

tpls_dir=$1
if [ "$tpls_dir" = "" ]; then
    tpls_dir="../../../tpls"
fi
cd $tpls_dir
tpls_dir=`pwd`
shift

# Set the common arguments for the TPLs makefile calls: the MFEM source and
# build directories. Also, when building MFEM, do not redirect the output to log
# files.
tpls_args=(MFEM_SRC=$mfem_dir MFEM_DIR=$mfem_dir SHOW_MFEM=YES)

# Parallel build
cd $tpls_dir
make "${tpls_args[@]}" mfem-clean
make "${tpls_args[@]}" mfem-full -j $build_np
cd $mfem_dir
make all -j $build_np
make test
