#!/bin/bash

set -e

# cling is installed here (in bin) and will look in {dir}/include and {dir}/lib
# without extra intervention
install_dir=/srv/conda/envs/notebook
mkdir -p $install_dir

# build and install mfem
git clone https://github.com/mfem/mfem.git
pushd mfem
make serial SHARED=YES -j8
make install PREFIX=$install_dir
popd

# include xeus-glvis
git clone https://github.com/GLVis/xeus-glvis.git
pushd xeus-glvis
make install prefix=$install_dir/include/glvis
popd
