# CMake generated Testfile for 
# Source directory: /Users/ben/Documents/SoftwareLibraries/mfem/examples
# Build directory: /Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ex1_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex1" "-no-vis")
add_test(ex2_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex2" "-no-vis")
add_test(ex3_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex3" "-no-vis")
add_test(ex4_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex4" "-no-vis")
add_test(ex5_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex5" "-no-vis")
add_test(ex6_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex6" "-no-vis")
add_test(ex7_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex7" "-no-vis")
add_test(ex8_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex8" "-no-vis")
add_test(ex9_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex9" "-no-vis")
add_test(ex10_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex10" "-no-vis" "-tf" "5")
add_test(ex14_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex14" "-no-vis")
add_test(ex15_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex15" "-no-vis" "-e" "1")
add_test(ex16_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex16" "-no-vis")
add_test(ex17_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex17" "-no-vis")
add_test(ex18_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex18" "-no-vis")
add_test(ex19_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex19" "-no-vis")
add_test(ex20_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex20" "-no-vis")
add_test(ex21_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex21" "-no-vis")
add_test(ex23_ser "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex23" "-no-vis")
add_test(ex1p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex1p" "-no-vis")
add_test(ex2p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex2p" "-no-vis")
add_test(ex3p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex3p" "-no-vis")
add_test(ex4p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex4p" "-no-vis")
add_test(ex5p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex5p" "-no-vis")
add_test(ex6p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex6p" "-no-vis")
add_test(ex7p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex7p" "-no-vis")
add_test(ex8p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex8p" "-no-vis")
add_test(ex9p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex9p" "-no-vis")
add_test(ex10p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex10p" "-no-vis" "-tf" "5")
add_test(ex11p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex11p" "-no-vis")
add_test(ex12p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex12p" "-no-vis")
add_test(ex13p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex13p" "-no-vis")
add_test(ex14p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex14p" "-no-vis")
add_test(ex15p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex15p" "-no-vis" "-e" "1")
add_test(ex16p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex16p" "-no-vis")
add_test(ex17p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex17p" "-no-vis")
add_test(ex18p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex18p" "-no-vis")
add_test(ex19p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex19p" "-no-vis")
add_test(ex20p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex20p" "-no-vis")
add_test(ex21p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex21p" "-no-vis")
add_test(ex23p_np=4 "/usr/local/bin/mpiexec" "-np" "4" "/Users/ben/Documents/SoftwareLibraries/mfem/bens_build/examples/ex23p" "-no-vis")
