# CMake generated Testfile for 
# Source directory: /g/g19/bs/quartz/mfem/examples
# Build directory: /g/g19/bs/quartz/mfem/bens_build/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(ex1_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex1" "-no-vis")
ADD_TEST(ex2_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex2" "-no-vis")
ADD_TEST(ex3_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex3" "-no-vis")
ADD_TEST(ex4_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex4" "-no-vis")
ADD_TEST(ex5_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex5" "-no-vis")
ADD_TEST(ex6_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex6" "-no-vis")
ADD_TEST(ex7_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex7" "-no-vis")
ADD_TEST(ex8_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex8" "-no-vis")
ADD_TEST(ex9_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex9" "-no-vis")
ADD_TEST(ex10_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex10" "-no-vis" "-tf" "5")
ADD_TEST(ex14_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex14" "-no-vis")
ADD_TEST(ex15_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex15" "-no-vis" "-e" "1")
ADD_TEST(ex16_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex16" "-no-vis")
ADD_TEST(ex17_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex17" "-no-vis")
ADD_TEST(ex18_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex18" "-no-vis")
ADD_TEST(ex19_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex19" "-no-vis")
ADD_TEST(ex20_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex20" "-no-vis")
ADD_TEST(ex21_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex21" "-no-vis")
ADD_TEST(ex23_ser "/g/g19/bs/quartz/mfem/bens_build/examples/ex23" "-no-vis")
ADD_TEST(ex1p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex1p" "-no-vis")
ADD_TEST(ex2p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex2p" "-no-vis")
ADD_TEST(ex3p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex3p" "-no-vis")
ADD_TEST(ex4p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex4p" "-no-vis")
ADD_TEST(ex5p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex5p" "-no-vis")
ADD_TEST(ex6p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex6p" "-no-vis")
ADD_TEST(ex7p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex7p" "-no-vis")
ADD_TEST(ex8p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex8p" "-no-vis")
ADD_TEST(ex9p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex9p" "-no-vis")
ADD_TEST(ex10p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex10p" "-no-vis" "-tf" "5")
ADD_TEST(ex11p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex11p" "-no-vis")
ADD_TEST(ex12p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex12p" "-no-vis")
ADD_TEST(ex13p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex13p" "-no-vis")
ADD_TEST(ex14p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex14p" "-no-vis")
ADD_TEST(ex15p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex15p" "-no-vis" "-e" "1")
ADD_TEST(ex16p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex16p" "-no-vis")
ADD_TEST(ex17p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex17p" "-no-vis")
ADD_TEST(ex18p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex18p" "-no-vis")
ADD_TEST(ex19p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex19p" "-no-vis")
ADD_TEST(ex20p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex20p" "-no-vis")
ADD_TEST(ex21p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex21p" "-no-vis")
ADD_TEST(ex23p_np=4 "/usr/bin/srun" "-np" "4" "/g/g19/bs/quartz/mfem/bens_build/examples/ex23p" "-no-vis")
