// Copyright (c) 2010-2025, Lawrence Livermore National Security, LLC. Produced
// at the Lawrence Livermore National Laboratory. All Rights reserved. See files
// LICENSE and NOTICE for details. LLNL-CODE-806117.
//
// This file is part of the MFEM library. For more information and source code
// availability visit https://mfem.org.
//
// MFEM is free software; you can redistribute it and/or modify it under the
// terms of the BSD-3 license. We welcome feedback and contributions, see file
// CONTRIBUTING.md for details.

#include "mfem.hpp"
#include "unit_tests.hpp"

#include <memory>

using namespace mfem;

namespace darcy_extension
{

// The lifting that transfers a Dirichlet datum from the true boundary Gamma to
// the computational boundary Gamma_h is the only new geometric object in the
// extension-from-subdomains method, and everything downstream is wrong if its
// orientation, its sign or its path family is wrong.  It admits an exact test,
// which is what these cases are: the path integral of C u = -grad p from x to
// xbar is p(x) - p(xbar) *whatever the path*, because C u is a gradient, so
// the lifted datum must reproduce the exact potential on Gamma_h.  With a
// polynomial potential the line quadrature is exact too and the agreement is
// to round-off, which leaves no room for a sign to be right by accident.

// -- The domain ---------------------------------------------------------------

// Omega is the disc of radius R about c, immersed in a background mesh of the
// unit square.  The level set is the signed distance, so that the offset that
// selects the subdomain means a distance.
const real_t disc_R = 0.45;
static void DiscCentre(Vector &c) { c.SetSize(2); c = 0.5; }

real_t DiscPhi(const Vector &x)
{
   Vector c; DiscCentre(c);
   return std::sqrt((x(0)-c(0))*(x(0)-c(0)) + (x(1)-c(1))*(x(1)-c(1))) - disc_R;
}

// -- Manufactured data --------------------------------------------------------

// K = I throughout, so C = K^-1 = I and u = -grad p.

// Degree two, so that a projection onto P^k with k >= 2 is exact and a Gauss
// rule of order two integrates it along a path exactly.
real_t pPoly(const Vector &x)
{ return 1. - 2.*x(0) + 3.*x(1) + x(0)*x(0)*x(1); }
void uPoly(const Vector &x, Vector &u)
{ u.SetSize(2); u(0) = 2. - 2.*x(0)*x(1); u(1) = -3. - x(0)*x(0); }

real_t pSin(const Vector &x) { return std::sin(x(0)) * std::sin(x(1)); }
void uSin(const Vector &x, Vector &u)
{
   u.SetSize(2);
   u(0) = -std::cos(x(0)) * std::sin(x(1));
   u(1) = -std::sin(x(0)) * std::cos(x(1));
}

// -- The computational subdomain ----------------------------------------------

struct Subdomain
{
   std::unique_ptr<Mesh> background;
   std::unique_ptr<SubMesh> D_h;
   int gamma_h_attr{};
};

/// Build D_h as the elements of an n x n triangulation of the unit square that
/// lie entirely inside the disc, pushed in by @a offset.
Subdomain BuildSubdomain(int n, real_t offset = 0.)
{
   Subdomain s;
   s.background = std::make_unique<Mesh>(
                     Mesh::MakeCartesian2D(n, n, Element::TRIANGLE));

   Array<int> marker;
   const int count = MarkLevelSetSubdomain(*s.background, DiscPhi, offset,
                                           marker);
   REQUIRE(count > 0);

   for (int i = 0; i < s.background->GetNE(); i++)
   {
      s.background->SetAttribute(i, marker[i] ? 1 : 2);
   }
   s.background->SetAttributes();

   Array<int> domain_attr(1);
   domain_attr[0] = 1;
   s.D_h = std::make_unique<SubMesh>(
              SubMesh::CreateFromDomain(*s.background, domain_attr));

   // D_h lies strictly inside the square, so the whole of its boundary is
   // generated by the extraction and carries the one new attribute.  Anything
   // else means an element of D_h touches the boundary of the background mesh,
   // which this test is not set up for.
   REQUIRE(s.D_h->bdr_attributes.Size() == 1);
   s.gamma_h_attr = s.D_h->bdr_attributes.Max();

   return s;
}

// -- The measurement ----------------------------------------------------------

/// Builds the evaluator of C u for one boundary face of Gamma_h.
using FluxFactory =
   std::function<VectorPositionFunction(FaceElementTransformations &)>;

/// The datum g on Gamma, lifted to Gamma_h, against the exact potential there.
struct LiftingError
{
   real_t l2{};
   real_t max{};
   real_t length{};
};

LiftingError MeasureLifting(Mesh &D_h, int gamma_h_attr,
                            const TransferPath &path, const FluxFactory &flux,
                            real_t (*p_exact)(const Vector &), int ir_order)
{
   const IntegrationRule &line_ir = IntRules.Get(Geometry::SEGMENT, ir_order);
   LiftingError e;
   Vector x, xbar;

   for (int be = 0; be < D_h.GetNBE(); be++)
   {
      if (D_h.GetBdrAttribute(be) != gamma_h_attr) { continue; }

      FaceElementTransformations *FTr = D_h.GetBdrFaceTransformations(be);
      if (!FTr) { continue; }

      const VectorPositionFunction Cu = flux(*FTr);
      const IntegrationRule &fir = IntRules.Get(FTr->GetGeometryType(), ir_order);

      for (int q = 0; q < fir.GetNPoints(); q++)
      {
         const IntegrationPoint &ip = fir.IntPoint(q);

         path.Endpoint(*FTr, ip, xbar);
         FTr->Transform(ip, x);

         // The datum on Gamma is the exact potential there.
         const real_t phi_h = p_exact(xbar) + PathIntegral(Cu, x, xbar, line_ir);
         const real_t err = phi_h - p_exact(x);
         const real_t w = ip.weight * FTr->Weight();

         e.l2 += w * err * err;
         e.length += w;
         e.max = std::max(e.max, std::abs(err));
      }
   }

   e.l2 = std::sqrt(e.l2);
   return e;
}

/// C u evaluated from the exact solution, wherever the point lies.
FluxFactory ExactFlux(void (*u)(const Vector &, Vector &))
{
   return [u](FaceElementTransformations &) -> VectorPositionFunction
   {
      return [u](const Vector &y, Vector &v) { u(y, v); };
   };
}

/// C u evaluated from the extension of a discrete flux out of the element that
/// owns the face.  The element transformation is owned rather than borrowed,
/// because Mesh::GetElementTransformation() hands out a shared object.
struct ExtensionState
{
   IsoparametricTransformation Tr;
   ElementExtension ext;
   int el{};
};

FluxFactory ExtendedFlux(const GridFunction &u_h)
{
   const FiniteElementSpace *fes = u_h.FESpace();
   return [&u_h, fes](FaceElementTransformations &FTr) -> VectorPositionFunction
   {
      auto st = std::make_shared<ExtensionState>();
      st->el = FTr.Elem1No;
      fes->GetMesh()->GetElementTransformation(st->el, &st->Tr);
      st->ext.SetElement(st->Tr);

      return [st, &u_h](const Vector &y, Vector &v)
      {
         IntegrationPoint ip;
         const bool ok = st->ext.TransformBack(y, ip);
         MFEM_VERIFY(ok, "the inverse element transformation did not converge");
         u_h.GetVectorValue(st->el, ip, v);
      };
   };
}

/// The same, but through the library's default inverse transformation, which
/// restricts its iterates to the reference element.  Only used to show that
/// the restriction is not harmless: see the test below.
FluxFactory ClampedFlux(const GridFunction &u_h)
{
   const FiniteElementSpace *fes = u_h.FESpace();
   return [&u_h, fes](FaceElementTransformations &FTr) -> VectorPositionFunction
   {
      auto st = std::make_shared<ExtensionState>();
      st->el = FTr.Elem1No;
      fes->GetMesh()->GetElementTransformation(st->el, &st->Tr);

      return [st, &u_h](const Vector &y, Vector &v)
      {
         IntegrationPoint ip;
         st->Tr.TransformBack(y, ip);
         u_h.GetVectorValue(st->el, ip, v);
      };
   };
}

// -- The cases ----------------------------------------------------------------

TEST_CASE("Extension from subdomains: the subdomain",
          "[DarcyExtension]")
{
   // Pushing the level set in must never grow the subdomain.
   int last = -1;
   for (real_t offset : {0.0, 0.02, 0.05, 0.1})
   {
      Mesh mesh = Mesh::MakeCartesian2D(16, 16, Element::TRIANGLE);
      Array<int> marker;
      const int count = MarkLevelSetSubdomain(mesh, DiscPhi, offset, marker);

      REQUIRE(count > 0);
      REQUIRE(count < mesh.GetNE());
      if (last >= 0) { REQUIRE(count <= last); }
      last = count;

      // Every selected element has all of its vertices inside.
      Array<int> vert;
      Vector x(2);
      for (int i = 0; i < mesh.GetNE(); i++)
      {
         if (!marker[i]) { continue; }
         mesh.GetElementVertices(i, vert);
         for (int v = 0; v < vert.Size(); v++)
         {
            const real_t *c = mesh.GetVertex(vert[v]);
            x(0) = c[0]; x(1) = c[1];
            REQUIRE(DiscPhi(x) <= -offset);
         }
      }
   }
}

TEST_CASE("Extension from subdomains: the lifting is exact for the exact flux",
          "[DarcyExtension]")
{
   // The path integral of C u is p(x) - p(a(x)) for any path, so the lifted
   // datum is the exact potential on Gamma_h.  Nothing here is discretized:
   // this fixes the orientation of the path, the sign of the integral and the
   // direction of the tangent, all at once.
   const int n = GENERATE(8, 16);
   const int ir_order = 8;

   Subdomain s = BuildSubdomain(n);

   Vector c; DiscCentre(c);
   ClosestPointPath cp_path(ClosestPointPath::Sphere(c, disc_R));
   LevelSetPath ls_path(DiscPhi, 3.0 / n);

   for (const TransferPath *path :
        { (const TransferPath *)&cp_path, (const TransferPath *)&ls_path })
   {
      const LiftingError e =
         MeasureLifting(*s.D_h, s.gamma_h_attr, *path, ExactFlux(uPoly),
                        pPoly, ir_order);

      CAPTURE(n, e.l2, e.max, e.length);
      REQUIRE(e.length > 0.);
      REQUIRE(e.max < 1e-12);
   }
}

TEST_CASE("Extension from subdomains: the extension of an exactly "
          "represented flux",
          "[DarcyExtension]")
{
   // The manufactured flux is a polynomial of degree two, so for k >= 2 the
   // discrete flux equals it on the element and, the elements being affine,
   // its extension equals it outside the element too.  The lifting is then
   // exact again -- and that is the whole content of the extension operator.
   const int n = 12;
   const int order = GENERATE(2, 3);
   const int ir_order = 8;

   Subdomain s = BuildSubdomain(n);

   L2_FECollection fec(order, 2, BasisType::GaussLobatto);
   FiniteElementSpace fes(s.D_h.get(), &fec, 2);
   GridFunction u_h(&fes);
   VectorFunctionCoefficient ucoeff(2, uPoly);
   u_h.ProjectCoefficient(ucoeff);

   Vector c; DiscCentre(c);
   ClosestPointPath path(ClosestPointPath::Sphere(c, disc_R));

   const LiftingError e =
      MeasureLifting(*s.D_h, s.gamma_h_attr, path, ExtendedFlux(u_h), pPoly,
                     ir_order);

   CAPTURE(order, e.l2, e.max);
   REQUIRE(e.max < 1e-11);
}

TEST_CASE("Extension from subdomains: the reference element must not be "
          "clamped",
          "[DarcyExtension]")
{
   // ElementTransformation::TransformBack() uses the default
   // NewtonElementProject solver, which projects each iterate back into the
   // reference element.  A point outside then comes back as the nearest point
   // of the element boundary and the extension is not the polynomial at all.
   // The failure is silent -- the call reports Outside and returns a
   // perfectly well-formed integration point -- so it is pinned here.
   const int n = 12;
   const int order = 2;
   const int ir_order = 8;

   Subdomain s = BuildSubdomain(n);

   L2_FECollection fec(order, 2, BasisType::GaussLobatto);
   FiniteElementSpace fes(s.D_h.get(), &fec, 2);
   GridFunction u_h(&fes);
   VectorFunctionCoefficient ucoeff(2, uPoly);
   u_h.ProjectCoefficient(ucoeff);

   Vector c; DiscCentre(c);
   ClosestPointPath path(ClosestPointPath::Sphere(c, disc_R));

   const LiftingError good =
      MeasureLifting(*s.D_h, s.gamma_h_attr, path, ExtendedFlux(u_h), pPoly,
                     ir_order);
   const LiftingError clamped =
      MeasureLifting(*s.D_h, s.gamma_h_attr, path, ClampedFlux(u_h), pPoly,
                     ir_order);

   CAPTURE(good.max, clamped.max);
   REQUIRE(good.max < 1e-11);
   REQUIRE(clamped.max > 1e3 * good.max);
}

TEST_CASE("Extension from subdomains: the lifting converges",
          "[DarcyExtension]")
{
   // With a potential that no polynomial reproduces, the error of the lifted
   // datum on Gamma_h is the path integral of the flux error over a path of
   // length O(h).  The rate is measured rather than assumed.
   const int order = GENERATE(0, 1, 2);
   const int ir_order = 2 * order + 8;

   Vector c; DiscCentre(c);
   ClosestPointPath path(ClosestPointPath::Sphere(c, disc_R));

   real_t prev = 0.;
   real_t rate = 0.;
   for (int n : {16, 32, 64})
   {
      Subdomain s = BuildSubdomain(n);

      L2_FECollection fec(order, 2, BasisType::GaussLobatto);
      FiniteElementSpace fes(s.D_h.get(), &fec, 2);
      GridFunction u_h(&fes);
      VectorFunctionCoefficient ucoeff(2, uSin);
      u_h.ProjectCoefficient(ucoeff);

      const LiftingError e =
         MeasureLifting(*s.D_h, s.gamma_h_attr, path, ExtendedFlux(u_h), pSin,
                        ir_order);

      if (prev > 0.) { rate = std::log2(prev / e.l2); }
      INFO("order " << order << " n " << n << " l2 " << e.l2
           << " rate " << rate);
      prev = e.l2;
   }

   REQUIRE(rate > order + 0.8);
}

} // namespace darcy_extension
