// Copyright (c) 2010-2025, Lawrence Livermore National Security, LLC. Produced
// at the Lawrence Livermore National Laboratory. All Rights reserved. See files
// LICENSE and NOTICE for details. LLNL-CODE-806117.
//
// This file is part of the MFEM library. For more information and source code
// availability visit https://mfem.org.
//
// MFEM is free software; you can redistribute it and/or modify it under the
// terms of the BSD-3 license. We welcome feedback and contributions, see file
// CONTRIBUTING.md for details.

#include "mfem.hpp"
#include "unit_tests.hpp"

#include <memory>
#include <complex>

using namespace mfem;

namespace darcy_extension
{

// The lifting that transfers a Dirichlet datum from the true boundary Gamma to
// the computational boundary Gamma_h is the only new geometric object in the
// extension-from-subdomains method, and everything downstream is wrong if its
// orientation, its sign or its path family is wrong.  It admits an exact test,
// which is what these cases are: the path integral of C u = -grad p from x to
// xbar is p(x) - p(xbar) *whatever the path*, because C u is a gradient, so
// the lifted datum must reproduce the exact potential on Gamma_h.  With a
// polynomial potential the line quadrature is exact too and the agreement is
// to round-off, which leaves no room for a sign to be right by accident.

// -- The domain ---------------------------------------------------------------

// Omega is the disc of radius R about c, immersed in a background mesh of the
// unit square.  The level set is the signed distance, so that the offset that
// selects the subdomain means a distance.
const real_t disc_R = 0.45;
static void DiscCentre(Vector &c) { c.SetSize(2); c = 0.5; }

real_t DiscPhi(const Vector &x)
{
   Vector c; DiscCentre(c);
   return std::sqrt((x(0)-c(0))*(x(0)-c(0)) + (x(1)-c(1))*(x(1)-c(1))) - disc_R;
}

// -- Manufactured data --------------------------------------------------------

// K = I throughout, so C = K^-1 = I and u = -grad p.

// Degree two, so that a projection onto P^k with k >= 2 is exact and a Gauss
// rule of order two integrates it along a path exactly.
real_t pPoly(const Vector &x)
{ return 1. - 2.*x(0) + 3.*x(1) + x(0)*x(0)*x(1); }
void uPoly(const Vector &x, Vector &u)
{ u.SetSize(2); u(0) = 2. - 2.*x(0)*x(1); u(1) = -3. - x(0)*x(0); }

real_t pSin(const Vector &x) { return std::sin(x(0)) * std::sin(x(1)); }
void uSin(const Vector &x, Vector &u)
{
   u.SetSize(2);
   u(0) = -std::cos(x(0)) * std::sin(x(1));
   u(1) = -std::sin(x(0)) * std::cos(x(1));
}

// -- The computational subdomain ----------------------------------------------

struct Subdomain
{
   std::unique_ptr<Mesh> background;
   std::unique_ptr<SubMesh> D_h;
   int gamma_h_attr{};
};

/// Build D_h as the elements of an n x n triangulation of the unit square that
/// lie entirely inside the disc, pushed in by @a offset.
Subdomain BuildSubdomain(int n, real_t offset = 0.)
{
   Subdomain s;
   s.background = std::make_unique<Mesh>(
                     Mesh::MakeCartesian2D(n, n, Element::TRIANGLE));

   Array<int> marker;
   const int count = MarkLevelSetSubdomain(*s.background, DiscPhi, offset,
                                           marker);
   REQUIRE(count > 0);

   for (int i = 0; i < s.background->GetNE(); i++)
   {
      s.background->SetAttribute(i, marker[i] ? 1 : 2);
   }
   s.background->SetAttributes();

   Array<int> domain_attr(1);
   domain_attr[0] = 1;
   s.D_h = std::make_unique<SubMesh>(
              SubMesh::CreateFromDomain(*s.background, domain_attr));

   // D_h lies strictly inside the square, so the whole of its boundary is
   // generated by the extraction and carries the one new attribute.  Anything
   // else means an element of D_h touches the boundary of the background mesh,
   // which this test is not set up for.
   REQUIRE(s.D_h->bdr_attributes.Size() == 1);
   s.gamma_h_attr = s.D_h->bdr_attributes.Max();

   return s;
}

// -- The measurement ----------------------------------------------------------

/// Builds the evaluator of C u for one boundary face of Gamma_h.
using FluxFactory =
   std::function<VectorPositionFunction(FaceElementTransformations &)>;

/// The datum g on Gamma, lifted to Gamma_h, against the exact potential there.
struct LiftingError
{
   real_t l2{};
   real_t max{};
   real_t length{};
};

LiftingError MeasureLifting(Mesh &D_h, int gamma_h_attr,
                            const TransferPath &path, const FluxFactory &flux,
                            real_t (*p_exact)(const Vector &), int ir_order)
{
   const IntegrationRule &line_ir = IntRules.Get(Geometry::SEGMENT, ir_order);
   LiftingError e;
   Vector x, xbar;

   for (int be = 0; be < D_h.GetNBE(); be++)
   {
      if (D_h.GetBdrAttribute(be) != gamma_h_attr) { continue; }

      FaceElementTransformations *FTr = D_h.GetBdrFaceTransformations(be);
      if (!FTr) { continue; }

      const VectorPositionFunction Cu = flux(*FTr);
      const IntegrationRule &fir = IntRules.Get(FTr->GetGeometryType(), ir_order);

      for (int q = 0; q < fir.GetNPoints(); q++)
      {
         const IntegrationPoint &ip = fir.IntPoint(q);

         path.Endpoint(*FTr, ip, xbar);
         FTr->Transform(ip, x);

         // The datum on Gamma is the exact potential there.
         const real_t phi_h = p_exact(xbar) + PathIntegral(Cu, x, xbar, line_ir);
         const real_t err = phi_h - p_exact(x);
         const real_t w = ip.weight * FTr->Weight();

         e.l2 += w * err * err;
         e.length += w;
         e.max = std::max(e.max, std::abs(err));
      }
   }

   e.l2 = std::sqrt(e.l2);
   return e;
}

/// C u evaluated from the exact solution, wherever the point lies.
FluxFactory ExactFlux(void (*u)(const Vector &, Vector &))
{
   return [u](FaceElementTransformations &) -> VectorPositionFunction
   {
      return [u](const Vector &y, Vector &v) { u(y, v); };
   };
}

/// C u evaluated from the extension of a discrete flux out of the element that
/// owns the face.  The element transformation is owned rather than borrowed,
/// because Mesh::GetElementTransformation() hands out a shared object.
struct ExtensionState
{
   IsoparametricTransformation Tr;
   ElementExtension ext;
   int el{};
};

FluxFactory ExtendedFlux(const GridFunction &u_h)
{
   const FiniteElementSpace *fes = u_h.FESpace();
   return [&u_h, fes](FaceElementTransformations &FTr) -> VectorPositionFunction
   {
      auto st = std::make_shared<ExtensionState>();
      st->el = FTr.Elem1No;
      fes->GetMesh()->GetElementTransformation(st->el, &st->Tr);
      st->ext.SetElement(st->Tr);

      return [st, &u_h](const Vector &y, Vector &v)
      {
         IntegrationPoint ip;
         const bool ok = st->ext.TransformBack(y, ip);
         MFEM_VERIFY(ok, "the inverse element transformation did not converge");
         u_h.GetVectorValue(st->el, ip, v);
      };
   };
}

/// The same, but through the library's default inverse transformation, which
/// restricts its iterates to the reference element.  Only used to show that
/// the restriction is not harmless: see the test below.
FluxFactory ClampedFlux(const GridFunction &u_h)
{
   const FiniteElementSpace *fes = u_h.FESpace();
   return [&u_h, fes](FaceElementTransformations &FTr) -> VectorPositionFunction
   {
      auto st = std::make_shared<ExtensionState>();
      st->el = FTr.Elem1No;
      fes->GetMesh()->GetElementTransformation(st->el, &st->Tr);

      return [st, &u_h](const Vector &y, Vector &v)
      {
         IntegrationPoint ip;
         st->Tr.TransformBack(y, ip);
         u_h.GetVectorValue(st->el, ip, v);
      };
   };
}

// -- The cases ----------------------------------------------------------------

TEST_CASE("Extension from subdomains: the subdomain",
          "[DarcyExtension]")
{
   // Pushing the level set in must never grow the subdomain.
   int last = -1;
   for (real_t offset : {0.0, 0.02, 0.05, 0.1})
   {
      Mesh mesh = Mesh::MakeCartesian2D(16, 16, Element::TRIANGLE);
      Array<int> marker;
      const int count = MarkLevelSetSubdomain(mesh, DiscPhi, offset, marker);

      REQUIRE(count > 0);
      REQUIRE(count < mesh.GetNE());
      if (last >= 0) { REQUIRE(count <= last); }
      last = count;

      // Every selected element has all of its vertices inside.
      Array<int> vert;
      Vector x(2);
      for (int i = 0; i < mesh.GetNE(); i++)
      {
         if (!marker[i]) { continue; }
         mesh.GetElementVertices(i, vert);
         for (int v = 0; v < vert.Size(); v++)
         {
            const real_t *c = mesh.GetVertex(vert[v]);
            x(0) = c[0]; x(1) = c[1];
            REQUIRE(DiscPhi(x) <= -offset);
         }
      }
   }
}

TEST_CASE("Extension from subdomains: the lifting is exact for the exact flux",
          "[DarcyExtension]")
{
   // The path integral of C u is p(x) - p(a(x)) for any path, so the lifted
   // datum is the exact potential on Gamma_h.  Nothing here is discretized:
   // this fixes the orientation of the path, the sign of the integral and the
   // direction of the tangent, all at once.
   const int n = GENERATE(8, 16);
   const int ir_order = 8;

   Subdomain s = BuildSubdomain(n);

   Vector c; DiscCentre(c);
   ClosestPointPath cp_path(ClosestPointPath::Sphere(c, disc_R));
   LevelSetPath ls_path(DiscPhi, 3.0 / n);

   for (const TransferPath *path :
        { (const TransferPath *)&cp_path, (const TransferPath *)&ls_path })
   {
      const LiftingError e =
         MeasureLifting(*s.D_h, s.gamma_h_attr, *path, ExactFlux(uPoly),
                        pPoly, ir_order);

      CAPTURE(n, e.l2, e.max, e.length);
      REQUIRE(e.length > 0.);
      REQUIRE(e.max < 1e-12);
   }
}

TEST_CASE("Extension from subdomains: the extension of an exactly "
          "represented flux",
          "[DarcyExtension]")
{
   // The manufactured flux is a polynomial of degree two, so for k >= 2 the
   // discrete flux equals it on the element and, the elements being affine,
   // its extension equals it outside the element too.  The lifting is then
   // exact again -- and that is the whole content of the extension operator.
   const int n = 12;
   const int order = GENERATE(2, 3);
   const int ir_order = 8;

   Subdomain s = BuildSubdomain(n);

   L2_FECollection fec(order, 2, BasisType::GaussLobatto);
   FiniteElementSpace fes(s.D_h.get(), &fec, 2);
   GridFunction u_h(&fes);
   VectorFunctionCoefficient ucoeff(2, uPoly);
   u_h.ProjectCoefficient(ucoeff);

   Vector c; DiscCentre(c);
   ClosestPointPath path(ClosestPointPath::Sphere(c, disc_R));

   const LiftingError e =
      MeasureLifting(*s.D_h, s.gamma_h_attr, path, ExtendedFlux(u_h), pPoly,
                     ir_order);

   CAPTURE(order, e.l2, e.max);
   REQUIRE(e.max < 1e-11);
}

TEST_CASE("Extension from subdomains: the reference element must not be "
          "clamped",
          "[DarcyExtension]")
{
   // ElementTransformation::TransformBack() uses the default
   // NewtonElementProject solver, which projects each iterate back into the
   // reference element.  A point outside then comes back as the nearest point
   // of the element boundary and the extension is not the polynomial at all.
   // The failure is silent -- the call reports Outside and returns a
   // perfectly well-formed integration point -- so it is pinned here.
   const int n = 12;
   const int order = 2;
   const int ir_order = 8;

   Subdomain s = BuildSubdomain(n);

   L2_FECollection fec(order, 2, BasisType::GaussLobatto);
   FiniteElementSpace fes(s.D_h.get(), &fec, 2);
   GridFunction u_h(&fes);
   VectorFunctionCoefficient ucoeff(2, uPoly);
   u_h.ProjectCoefficient(ucoeff);

   Vector c; DiscCentre(c);
   ClosestPointPath path(ClosestPointPath::Sphere(c, disc_R));

   const LiftingError good =
      MeasureLifting(*s.D_h, s.gamma_h_attr, path, ExtendedFlux(u_h), pPoly,
                     ir_order);
   const LiftingError clamped =
      MeasureLifting(*s.D_h, s.gamma_h_attr, path, ClampedFlux(u_h), pPoly,
                     ir_order);

   CAPTURE(good.max, clamped.max);
   REQUIRE(good.max < 1e-11);
   REQUIRE(clamped.max > 1e3 * good.max);
}

TEST_CASE("Extension from subdomains: the lifting converges",
          "[DarcyExtension]")
{
   // With a potential that no polynomial reproduces, the error of the lifted
   // datum on Gamma_h is the path integral of the flux error over a path of
   // length O(h).  The rate is measured rather than assumed.
   const int order = GENERATE(0, 1, 2);
   const int ir_order = 2 * order + 8;

   Vector c; DiscCentre(c);
   ClosestPointPath path(ClosestPointPath::Sphere(c, disc_R));

   real_t prev = 0.;
   real_t rate = 0.;
   for (int n : {16, 32, 64})
   {
      Subdomain s = BuildSubdomain(n);

      L2_FECollection fec(order, 2, BasisType::GaussLobatto);
      FiniteElementSpace fes(s.D_h.get(), &fec, 2);
      GridFunction u_h(&fes);
      VectorFunctionCoefficient ucoeff(2, uSin);
      u_h.ProjectCoefficient(ucoeff);

      const LiftingError e =
         MeasureLifting(*s.D_h, s.gamma_h_attr, path, ExtendedFlux(u_h), pSin,
                        ir_order);

      if (prev > 0.) { rate = std::log2(prev / e.l2); }
      INFO("order " << order << " n " << n << " l2 " << e.l2
           << " rate " << rate);
      prev = e.l2;
   }

   REQUIRE(rate > order + 0.8);
}

// -- Solving on the subdomain -------------------------------------------------

// C = I, so u = -grad p and the source of the potential equation is
// g = -div u = laplacian p.
real_t gSin(const Vector &x) { return -2.0 * pSin(x); }
real_t pSinNatural(const Vector &x) { return -pSin(x); }

struct SolveResult
{
   real_t err_u{}, err_p{};    ///< L2 errors on D_h
   real_t ext_u{}, ext_p{};    ///< and on its complement, normalized
   real_t area_err{};          ///< how far the swept measure is from the true
   bool converged{};
};

/// The measure of the disc less that of D_h, which the regions swept by the
/// paths must reproduce if they tile it.
real_t ComplementMeasure(Mesh &D_h)
{
   real_t vol = 0.;
   for (int i = 0; i < D_h.GetNE(); i++) { vol += D_h.GetElementVolume(i); }
   return M_PI * disc_R * disc_R - vol;
}

/// Solve the hybridized HDG problem on D_h. With @a extend the Dirichlet datum
/// is transferred from Gamma along the paths; otherwise it is read on Gamma_h
/// itself, which is the boundary-fitted problem on the same subdomain and so
/// is what the extension has to match.
///
/// @a ext_sign is exposed only so that the wrong sign can be shown to fail.
SolveResult SolveOnSubdomain(int n, int order, bool extend,
                             real_t tau = 1.0, real_t ext_sign = +1.0)
{
   const int dim = 2;
   Subdomain s = BuildSubdomain(n);

   Array<int> bdr_gamma_h(s.gamma_h_attr);
   bdr_gamma_h = 0;
   bdr_gamma_h[s.gamma_h_attr - 1] = 1;

   Vector c; DiscCentre(c);
   ClosestPointPath path(ClosestPointPath::Sphere(c, disc_R));

   L2_FECollection u_coll(order, dim, BasisType::GaussLobatto);
   L2_FECollection p_coll(order, dim);
   FiniteElementSpace fes_u(s.D_h.get(), &u_coll, dim);
   FiniteElementSpace fes_p(s.D_h.get(), &p_coll);

   ConstantCoefficient C(1.0);
   VectorFunctionCoefficient zero(dim, [](const Vector &, Vector &f) { f = 0.0; });
   FunctionCoefficient gcoeff(gSin);
   FunctionCoefficient pcoeff(pSin);
   VectorFunctionCoefficient ucoeff(dim, uSin);

   FunctionCoefficient datum_here(pSinNatural);
   PathTraceCoefficient datum_there(path, pSinNatural);
   Coefficient &datum = extend ? static_cast<Coefficient &>(datum_there)
                        : static_cast<Coefficient &>(datum_here);

   DarcyForm darcy(&fes_u, &fes_p);

   darcy.GetFluxMassForm()->AddDomainIntegrator(new VectorMassIntegrator(C));
   if (extend)
   {
      darcy.GetFluxMassForm()->AddBdrFaceIntegrator(
         new HDGExtensionIntegrator(path, C, ext_sign), bdr_gamma_h);
   }

   MixedBilinearForm *B = darcy.GetFluxDivForm();
   B->AddDomainIntegrator(new VectorDivergenceIntegrator());
   B->AddInteriorFaceIntegrator(
      new TransposeIntegrator(new DGNormalTraceIntegrator(-1.0)));

   // HDGDiffusionIntegrator's parameter is tau*h/kappa, so tau/n holds tau
   // fixed under refinement -- the scaling the reference uses, and the one
   // that gives k+1 in both variables.
   darcy.GetPotentialMassForm()->AddInteriorFaceIntegrator(
      new HDGDiffusionIntegrator(C, tau / n));

   LinearForm *fform = darcy.GetFluxRHS();
   fform->AddDomainIntegrator(new VectorDomainLFIntegrator(zero));
   fform->AddBdrFaceIntegrator(new VectorBoundaryFluxLFIntegrator(datum),
                               bdr_gamma_h);
   darcy.GetPotentialRHS()->AddDomainIntegrator(new DomainLFIntegrator(gcoeff));

   Array<int> ess_flux_tdofs;
   DG_Interface_FECollection trace_coll(order, dim);
   FiniteElementSpace fes_t(s.D_h.get(), &trace_coll);
   darcy.EnableHybridization(&fes_t, new NormalTraceJumpIntegrator(),
                             ess_flux_tdofs);

   darcy.Assemble();

   BlockVector x(darcy.GetOffsets());
   x = 0.0;

   OperatorPtr A;
   Vector X, RHS;
   darcy.FormLinearSystem(ess_flux_tdofs, x, A, X, RHS, true);

   GSSmoother prec;
   GMRESSolver solver;
   solver.SetKDim(500);
   solver.SetMaxIter(5000);
   solver.SetRelTol(0.0);
   solver.SetAbsTol(1e-12);
   solver.SetPreconditioner(prec);
   solver.SetOperator(*A);
   solver.Mult(RHS, X);

   SolveResult r;
   r.converged = solver.GetConverged();

   darcy.RecoverFEMSolution(X, x);
   GridFunction u_h, p_h;
   u_h.MakeRef(&fes_u, x.GetBlock(0), 0);
   p_h.MakeRef(&fes_p, x.GetBlock(1), 0);
   r.err_u = u_h.ComputeL2Error(ucoeff);
   r.err_p = p_h.ComputeL2Error(pcoeff);

   // The approximation on D_h^c: the flux is the extension of the element's
   // own polynomial, the potential the lifting evaluated there rather than
   // only on Gamma_h. This is the half of the claim that is about Omega and
   // not merely about D_h.
   const int iro = 2 * order + 8;
   const IntegrationRule &ir = IntRules.Get(Geometry::SEGMENT, iro);
   IsoparametricTransformation el_tr;
   ElementExtension ext;
   Vector ue(dim), v;
   real_t e2u = 0., e2p = 0., area = 0.;

   for (int be = 0; be < s.D_h->GetNBE(); be++)
   {
      FaceElementTransformations *FTr = s.D_h->GetBdrFaceTransformations(be);
      if (!FTr) { continue; }

      const int el = FTr->Elem1No;
      s.D_h->GetElementTransformation(el, &el_tr);
      ext.SetElement(el_tr);

      auto Cu = [&](const Vector &yy, Vector &vv)
      {
         IntegrationPoint eip;
         MFEM_VERIFY(ext.TransformBack(yy, eip), "no convergence");
         u_h.GetVectorValue(el, eip, vv);
      };

      ExtensionRegionQuadrature(*FTr, path, ir, ir,
                                [&](const ExtensionPoint &pt)
      {
         uSin(pt.y, ue);
         Cu(pt.y, v);
         real_t du = 0.;
         for (int d = 0; d < dim; d++)
         {
            const real_t q = ue(d) - v(d);
            du += q * q;
         }
         const real_t lift = pSin(pt.xbar) + PathIntegral(Cu, pt.y, pt.xbar, ir);
         const real_t dp = pSin(pt.y) - lift;

         e2u += pt.weight * du;
         e2p += pt.weight * dp * dp;
         area += pt.weight;
      });
   }

   const real_t vol_c = ComplementMeasure(*s.D_h);
   r.area_err = std::abs(area - vol_c) / vol_c;

   // Normalized by the measure, as the reference does: it shrinks like h, and
   // a raw L2 norm over it would carry half an order that says nothing about
   // the approximation.
   const real_t scale = (area > 0.) ? std::sqrt(area) : 1.;
   r.ext_u = std::sqrt(e2u) / scale;
   r.ext_p = std::sqrt(e2p) / scale;
   return r;
}

TEST_CASE("Extension from subdomains: the design order is retained",
          "[DarcyExtension][HDG]")
{
   // The claim of the method: solving on a subdomain whose boundary stands
   // O(h) from the true one, with the datum transferred along the paths, keeps
   // the k+1 of the boundary-fitted method in both variables. Earlier
   // techniques needed the distance to be O(h^(k+1)); here it halves with h
   // and no more.
   const int order = GENERATE(0, 1, 2);

   real_t prev_u = 0.0, prev_p = 0.0;
   real_t rate_u = 0.0, rate_p = 0.0;
   for (int n : {8, 16, 32})
   {
      const SolveResult r = SolveOnSubdomain(n, order, true);
      REQUIRE(r.converged);
      if (prev_u > 0.0)
      {
         rate_u = std::log2(prev_u / r.err_u);
         rate_p = std::log2(prev_p / r.err_p);
      }
      INFO("order " << order << " n " << n << " eu " << r.err_u
           << " ep " << r.err_p << " rate_u " << rate_u
           << " rate_p " << rate_p);
      prev_u = r.err_u;
      prev_p = r.err_p;
   }

   CAPTURE(order, rate_u, rate_p);
   REQUIRE(rate_u > order + 0.7);
   REQUIRE(rate_p > order + 0.7);
}

TEST_CASE("Extension from subdomains: the transfer costs almost nothing",
          "[DarcyExtension][HDG]")
{
   // Against the same subdomain solved with the datum read on Gamma_h itself,
   // which is the boundary-fitted problem the transfer is standing in for.
   // The ratio of the errors is the reference's measure of robustness, and it
   // tends to one from above as the mesh is refined.
   const int order = GENERATE(0, 1);

   real_t ratio_u = 0.0, ratio_p = 0.0;
   for (int n : {16, 32})
   {
      const SolveResult e = SolveOnSubdomain(n, order, true);
      const SolveResult c = SolveOnSubdomain(n, order, false);
      REQUIRE(e.converged);
      REQUIRE(c.converged);
      ratio_u = e.err_u / c.err_u;
      ratio_p = e.err_p / c.err_p;
      INFO("order " << order << " n " << n << " ratio_u " << ratio_u
           << " ratio_p " << ratio_p);
   }

   CAPTURE(order, ratio_u, ratio_p);
   REQUIRE(ratio_u < 1.5);
   REQUIRE(ratio_p < 1.05);
}

TEST_CASE("Extension from subdomains: the sign of the transfer is not free",
          "[DarcyExtension][HDG]")
{
   // The extension term is the solution-dependent half of the datum, moved to
   // the left, so its sign is the negative of the sign the datum enters the
   // flux right-hand side with. Reversing it does not degrade the method, it
   // destroys it: the error grows under refinement. Pinned because a sign that
   // is merely argued for is a sign that is eventually wrong.
   const int order = 1;

   const SolveResult good_c = SolveOnSubdomain(16, order, true, 1.0, +1.0);
   const SolveResult good_f = SolveOnSubdomain(32, order, true, 1.0, +1.0);
   const SolveResult bad_c  = SolveOnSubdomain(16, order, true, 1.0, -1.0);
   const SolveResult bad_f  = SolveOnSubdomain(32, order, true, 1.0, -1.0);

   CAPTURE(good_c.err_p, good_f.err_p, bad_c.err_p, bad_f.err_p);
   REQUIRE(good_f.err_p < 0.5 * good_c.err_p);
   REQUIRE(bad_f.err_p > 10.0 * good_f.err_p);
}

TEST_CASE("Extension from subdomains: the regions tile the complement",
          "[DarcyExtension]")
{
   // The regions swept by the paths are where the approximation on D_h^c
   // lives, and an integral over them is an integral over the complement only
   // if they tile it. That is a property of the path family, not of the
   // quadrature: adjacent faces must agree on the path through the vertex they
   // share.
   //
   // The closest-point map agrees, depending on the point and not on the face.
   // A family following each face's own normal does not, and this measures how
   // badly -- which is why CS-Extensions builds its general family by
   // interpolating the paths of the vertices instead.
   const int n = GENERATE(8, 16, 32);

   Subdomain s = BuildSubdomain(n);
   const real_t truth = ComplementMeasure(*s.D_h);
   REQUIRE(truth > 0.);

   Vector c; DiscCentre(c);
   ClosestPointPath cp(ClosestPointPath::Sphere(c, disc_R));
   LevelSetPath ls(DiscPhi, 4.0 / n);

   const IntegrationRule &ir = IntRules.Get(Geometry::SEGMENT, 20);

   real_t area[2] = {0., 0.};
   const TransferPath *paths[2] = { &cp, &ls };
   for (int k = 0; k < 2; k++)
   {
      for (int be = 0; be < s.D_h->GetNBE(); be++)
      {
         FaceElementTransformations *FTr = s.D_h->GetBdrFaceTransformations(be);
         if (!FTr) { continue; }
         ExtensionRegionQuadrature(*FTr, *paths[k], ir, ir,
                                   [&](const ExtensionPoint &pt)
         { area[k] += pt.weight; });
      }
   }

   CAPTURE(n, truth, area[0], area[1]);
   REQUIRE(std::abs(area[0] - truth) < 1e-8 * truth);
   REQUIRE(area[1] > 1.2 * truth);
}

TEST_CASE("Extension from subdomains: the approximation on the whole domain",
          "[DarcyExtension][HDG]")
{
   // What the method is for. On the region that was never meshed, the flux is
   // the extension of the element's polynomial and the potential is the
   // lifting; the first converges at k+1, and the second at k+2, which is what
   // the reference reports and follows from the potential being *defined*
   // there by an integral of the flux over a path of length O(h).
   const int order = GENERATE(0, 1, 2);

   real_t prev_u = 0.0, prev_p = 0.0;
   real_t rate_u = 0.0, rate_p = 0.0;
   for (int n : {8, 16, 32})
   {
      const SolveResult r = SolveOnSubdomain(n, order, true);
      REQUIRE(r.converged);
      REQUIRE(r.area_err < 1e-8);
      if (prev_u > 0.0)
      {
         rate_u = std::log2(prev_u / r.ext_u);
         rate_p = std::log2(prev_p / r.ext_p);
      }
      INFO("order " << order << " n " << n << " ext_u " << r.ext_u
           << " ext_p " << r.ext_p << " rate_u " << rate_u
           << " rate_p " << rate_p);
      prev_u = r.ext_u;
      prev_p = r.ext_p;
   }

   CAPTURE(order, rate_u, rate_p);
   REQUIRE(rate_u > order + 0.7);
   REQUIRE(rate_p > order + 1.7);
}

// -- The searched path family, and what it is for -----------------------------

// The Joukowsky airfoil of CS-Extensions section 3.4, whose tail is the
// feature that defeats the simpler families. The level set is the inverse of
// the map, taking the branch injective on |z| >= lambda.
const real_t foil_R = 0.107, foil_s1 = 0.01, foil_s2 = 0.01;

real_t FoilPhi(const Vector &x, real_t lambda)
{
   const std::complex<real_t> w(x(0) - 0.5, x(1) - 0.5);
   std::complex<real_t> r = std::sqrt(w * w - 4.0 * lambda * lambda);
   if (w.real() * r.real() + w.imag() * r.imag() < 0.0) { r = -r; }
   const std::complex<real_t> z = 0.5 * (w + r);
   return foil_R - std::abs(z - std::complex<real_t>(foil_s1, foil_s2));
}

/// The measure the paths sweep, against the truth, on any subdomain.
real_t SweptMeasure(Mesh &D_h, int gamma_h_attr, const TransferPath &path,
                    int ir_order = 20)
{
   const IntegrationRule &ir = IntRules.Get(Geometry::SEGMENT, ir_order);
   real_t area = 0.;
   for (int be = 0; be < D_h.GetNBE(); be++)
   {
      if (D_h.GetBdrAttribute(be) != gamma_h_attr) { continue; }
      FaceElementTransformations *FTr = D_h.GetBdrFaceTransformations(be);
      if (!FTr) { continue; }
      ExtensionRegionQuadrature(*FTr, path, ir, ir,
      [&](const ExtensionPoint &pt) { area += pt.weight; });
   }
   return area;
}

TEST_CASE("Extension from subdomains: the searched path family",
          "[DarcyExtension]")
{
   // VertexConePath chooses a direction at each vertex of Gamma_h by searching
   // a fan of rays, and interpolates along the faces. On a boundary that has a
   // closest-point map it is not needed, which makes that the place to check
   // it: it must land on Gamma, and it must tile, both of which the analytic
   // family does and neither of which follows from the search converging.
   const int n = GENERATE(8, 16);

   Subdomain s = BuildSubdomain(n);
   VertexConePath path(*s.D_h, s.gamma_h_attr, DiscPhi, 4.0 / n);

   // No vertex needed the admissible fan widened, so every path leaves D_h
   // through both of the faces meeting at its vertex: Assumption P.1 holds.
   REQUIRE(path.NumWidened() == 0);

   const IntegrationRule &ir = IntRules.Get(Geometry::SEGMENT, 10);
   Vector xbar;
   real_t worst = 0.;
   for (int be = 0; be < s.D_h->GetNBE(); be++)
   {
      if (s.D_h->GetBdrAttribute(be) != s.gamma_h_attr) { continue; }
      FaceElementTransformations *FTr = s.D_h->GetBdrFaceTransformations(be);
      if (!FTr) { continue; }
      for (int q = 0; q < ir.GetNPoints(); q++)
      {
         path.Endpoint(*FTr, ir.IntPoint(q), xbar);
         worst = std::max(worst, std::abs(DiscPhi(xbar)));
      }
   }
   CAPTURE(n, worst);
   REQUIRE(worst < 1e-10);

   const real_t truth = ComplementMeasure(*s.D_h);
   const real_t swept = SweptMeasure(*s.D_h, s.gamma_h_attr, path);
   CAPTURE(truth, swept);
   REQUIRE(std::abs(swept - truth) < 1e-8 * truth);
}

TEST_CASE("Extension from subdomains: a feature thinner than the mesh breaks "
          "the tiling",
          "[DarcyExtension]")
{
   // Measured on the reference's airfoil, and the sharpest statement this file
   // has about the limits of the construction. The Joukowsky parameter sets
   // how thin the tail is: at the reference's own value the shape closes into
   // a curled tail a fraction of a mesh width across, and there the
   // interpolated paths of neighbouring faces cross before reaching Gamma, so
   // their regions overlap and the swept measure comes out too large. Blunt
   // the tail and the same family tiles exactly.
   //
   // The overlap falls with the mesh -- 1.1e-2, 1.1e-2, 5.3e-3, 1.1e-3 as n
   // runs 16, 32, 64, 128 -- so it is a resolution effect and not a defect in
   // the family. Closing it needs the cone of CS-Extensions section 2.4.1,
   // which restricts the search to directions that cannot cross; only the
   // half-space part of that restriction is built.
   const int n = 32;
   const real_t thin = foil_R - std::sqrt(foil_s1 * foil_s1 + foil_s2 * foil_s2);
   const real_t blunt = 0.05;

   real_t rel[2] = {0., 0.};
   const real_t lambdas[2] = { thin, blunt };
   for (int k = 0; k < 2; k++)
   {
      const real_t lambda = lambdas[k];
      auto phi = [lambda](const Vector &x) { return FoilPhi(x, lambda); };

      Mesh background = Mesh::MakeCartesian2D(n, n, Element::TRIANGLE);
      Array<int> marker;
      REQUIRE(MarkLevelSetSubdomain(background, phi, 0., marker) > 0);
      for (int i = 0; i < background.GetNE(); i++)
      {
         background.SetAttribute(i, marker[i] ? 1 : 2);
      }
      background.SetAttributes();
      Array<int> domain_attr(1);
      domain_attr[0] = 1;
      SubMesh D_h = SubMesh::CreateFromDomain(background, domain_attr);

      const int gamma_h = D_h.bdr_attributes.Max();
      REQUIRE(gamma_h == background.bdr_attributes.Max() + 1);

      VertexConePath path(D_h, gamma_h, phi, 4.0 / n);

      // The area of the Joukowsky image, by the shoelace formula on it.
      const int N = 200000;
      const std::complex<real_t> c(foil_s1, foil_s2);
      real_t A = 0.;
      std::complex<real_t> prev = c + foil_R + lambda * lambda / (c + foil_R);
      for (int i = 1; i <= N; i++)
      {
         const std::complex<real_t> z =
            c + foil_R * std::exp(std::complex<real_t>(0., 2. * M_PI * i / N));
         const std::complex<real_t> w = z + lambda * lambda / z;
         A += prev.real() * w.imag() - w.real() * prev.imag();
         prev = w;
      }
      real_t vol_D = 0.;
      for (int i = 0; i < D_h.GetNE(); i++) { vol_D += D_h.GetElementVolume(i); }
      const real_t truth = (1. - 0.5 * std::abs(A)) - vol_D;

      rel[k] = (SweptMeasure(D_h, gamma_h, path) - truth) / truth;
   }

   CAPTURE(rel[0], rel[1]);
   REQUIRE(std::abs(rel[1]) < 1e-8);      // blunt: exact
   REQUIRE(rel[0] > 1e-3);                // the reference's tail: too large
}

} // namespace darcy_extension
