# if [[ `git status --porcelain` ]]; then
  # echo "There are uncommited changes. Abort."
# else
  rm *.o
  make simpl -j
  make oc -j
  BACKTRACK="-ab -bb"
  for back in $BACKTRACK
  do
    for p in 21 22
    do
      for i in 6 7 8
      do
        mpirun -np 8 ./simpl -rs $i -rp 0 -p $p -L2 -atol 5e-05 -rtol 5e-05 $back
      done
    done
  done
  # git add -f *.csv
  # git commit -m "Autogenerated commit from $(basename "$0")"
  # No changes
# fi
