# if [[ `git status --porcelain` ]]; then
  # echo "There are uncommited changes. Abort."
# else
rm *.o
make simpl oc mma -j
  BACKTRACK="-bb -ab"
  for back in $BACKTRACK
  do
    for p in 22
    do
      for i in 6 7
      do
        mpirun -np 8 ./simpl -rs $i -rp 0 -p $p $back -no-vis -vs 10 -atol 1e-05 -rtol 1e-04
      done
    done
  done
  # METHOD="oc mma"
  # for method in $METHOD
  # do
  #   mpirun -np 8 ./$method -rs 7 -rp 0 -p 22 -no-vis -vs 1
  # done
  # git add -f *.csv
  # git commit -m "Autogenerated commit from $(basename "$0")"
  # No changes
# fi

mpirun -np 8 ./simpl -rs 8 -rp 0 -p 22 -vs 1 -atol 2e-06 -rtol 1e-04 -bb
mpirun -np 8 ./simpl -rs 8 -rp 0 -p 22 -vs 1 -atol 2e-06 -rtol 1e-04 -ab
mpirun -np 8 ./oc -rs 8 -rp 0 -p 22 -vs 1 -atol 2e-06 -rtol 1e-04
mpirun -np 8 ./mma -rs 8 -rp 0 -p 22 -vs 1 -atol 2e-06 -rtol 1e-04

mpirun -np 8 ./simpl -rs 4 -rp 4 -p -21 -vs 1 -atol 1e-06 -rtol 1e-04 -bb
mpirun -np 8 ./simpl -rs 4 -rp 4 -p -21 -vs 1 -atol 1e-06 -rtol 1e-04 -ab
mpirun -np 8 ./simpl -rs 4 -rp 4 -p 24 -vs 1 -atol 1e-06 -rtol 1e-06 -bb
mpirun -np 8 ./simpl -rs 4 -rp 4 -p 24 -vs 1 -atol 1e-06 -rtol 1e-06 -ab

