# if [[ `git status --porcelain` ]]; then
  # echo "There are uncommited changes. Abort."
# else
  rm *.o
  make simpl -j
  make oc -j
  BACKTRACK="-bb -ab"
  for back in $BACKTRACK
  do
    for p in 22
    do
      for i in 7 8 9
      do
        mpirun -np 8 ./simpl -rs $i -rp 0 -p $p $back -no-vis -vs 1
      done
    done
  done
  # METHOD="oc mma"
  # for method in $METHOD
  # do
  #   mpirun -np 8 ./$method -rs 7 -rp 0 -p 22 -no-vis -vs 1
  # done
  # git add -f *.csv
  # git commit -m "Autogenerated commit from $(basename "$0")"
  # No changes
# fi

rm *.o
make simpl oc mma -j
mpirun -np 8 ./simpl -rs 7 -rp 0 -p 22 -vs 1
mpirun -np 8 ./simpl -rs 7 -rp 0 -p 22 -vs 1 -ab
mpirun -np 8 ./oc -rs 7 -rp 0 -p 22 -vs 1
mpirun -np 8 ./mma -rs 7 -rp 0 -p 22 -vs 1
