#!/bin/bash

CURRPATH=$PWD
cd $CURRPATH
#
cd $CURRPATH/../../../gslib
echo "cd `pwd`"
echo
make clean && make CC=mpicc MPI=1 -j
#
echo 
cd $CURRPATH/../../
echo "cd `pwd`"
echo
#
sleep 3
rm libmfem.a
make -j12 MFEM_USE_GSLIB=YES
#
cd $CURRPATH
# make psurffindpts_adi -j && mpirun -np 10 psurffindpts_adi -mo 4 -o 8 -eo 1 --npt 1000 -nx 32 --dim 3 -visit
# make psurffindpts_adi -j && mpirun -np 10 psurffindpts_adi -m ../meshing/blade.mesh -mo 2 -o 8 -eo 2 --npt 100000 -visit
# make psurffindpts_adi -j && mpirun -np 1 psurffindpts_adi -m ./star-surf.mesh -mo 2 -o 8 -eo 2 --npt 2 -visit
# make psurffindpts_adi -j && mpirun -np 10 psurffindpts_adi -m ./mfem-logo.mesh -mo 4 -o 8 -eo 2 --npt 2 -visit
# make psurffindpts_adi -j && mpirun -np 10 psurffindpts_adi -m ./klein-bottle.mesh -mo 3 -o 8 -eo 2 --npt 10000 -visit
make psurffindpts_adi -j && mpirun -np 10 psurffindpts_adi -m ./rocker_arm_hex.vtk -mo 3 -o 8 -eo 2 --npt 100 -visit
# make psurffindpts_adi -j && mpirun -np 1 psurffindpts_adi -m ./rhombus.mesh -mo 4 -o 8 -eo 2 --npt 2 -visit
# make psurffindpts_adi -j && mpirun -np 1 psurffindpts_adi -m ./deformededge2d.mesh -mo 2 -o 8 -eo 2 --npt 2 -visit
# make psurffindpts_adi -j && mpirun -np 1 psurffindpts_adi -m ./singlesurf3d.mesh -mo 2 -o 8 -eo 2 --npt 2 -visit
# make psurffindpts_adi -j && mpirun -np 1 psurffindpts_adi -m ./deformededge2d.mesh -mo 4 -o 8 -eo 2 --npt 2 -visit
# make psurffindpts_adi -j && mpirun -np 10 psurffindpts_adi -m ./toroid-hex-o3-s3.mesh -rs 2 -mo 3 -o 12 -eo 4 --npt 100 -visit
