#!/bin/bash

CURRPATH=$PWD
cd $CURRPATH
cd $HOME/src/gslib
make clean && make CC=mpicc MPI=1 -j
sleep 3
#
cd $HOME/src/mfem
rm libmfem.a && make -j10 MFEM_USE_GSLIB=YES
sleep 3
#
cd $CURRPATH
make psurffindpts_adi -j && mpirun -np 2 psurffindpts_adi -mo 2 -dim 2 -nx 2 -o 1 -vis

