#!/bin/bash

CURRPATH=$PWD
cd $CURRPATH
#
cd $CURRPATH/../../../gslib
echo "cd `pwd`"
echo
make clean && make CC=mpicc MPI=1 -j
#
echo 
cd $CURRPATH/../../
echo "cd `pwd`"
echo
#
sleep 3
rm libmfem.a && make -j10 MFEM_USE_GSLIB=YES

