//                    MFEM HDG Miniapp: extension from subdomains
//
// Compile with: make extension
//
// Sample runs:  extension -o 1 -n 8 -r 3
//               extension -o 2 -n 8 -r 3 -path ls
//               extension -o 3 -n 8 -r 3 -tau 1
//               extension -o 1 -n 16 -r 2 -no-ext
//
// Description:  Solves the Darcy problem
//
//                   C u + grad p = 0,   -div u = g   in Omega,   p = f on Gamma
//
//               on a *polyhedral subdomain* D_h of a domain Omega whose
//               boundary Gamma the mesh does not follow, by the extension
//               technique of Cockburn and Solano. The Dirichlet datum given on
//               Gamma is transferred to the computational boundary Gamma_h
//               along a family of paths, by the line integral
//
//                   phi_h(x) = f(a(x)) + int_sigma C E_h(u_h) . m ds,
//
//               where E_h is the extension of the discrete flux out of the
//               element owning the face. The curved boundary is thereby
//               reduced to the evaluation of line integrals, and the design
//               order of the method is retained even though the distance from
//               Gamma_h to Gamma is only of order h -- which is the whole
//               point, earlier techniques having needed order h^(k+1).
//
//               Omega is a disc immersed in a triangulated square, which is
//               the experiment of section 3.2 of the reference. The miniapp
//               solves on a sequence of background meshes and prints the
//               history of convergence, because the claim being tested is a
//               claim about rates. With -ctl it also solves, on the same D_h,
//               the problem whose Dirichlet datum is read on Gamma_h itself --
//               the boundary-fitted problem the extension is trying to match
//               -- and reports the ratio of the errors.
//
//               Reference: B. Cockburn and M. Solano, Solving Dirichlet
//               boundary-value problems on curved domains by extensions from
//               subdomains, SIAM J. Sci. Comput. 34 (2012) A497-A519.

#include "mfem.hpp"

#include <memory>
#include <iostream>
#include <iomanip>

using namespace std;
using namespace mfem;

namespace
{

// The domain: a disc, immersed in the unit square.
real_t disc_R = 0.45;
real_t disc_cx = 0.5, disc_cy = 0.5;

real_t LevelSet(const Vector &x)
{
   const real_t dx = x(0) - disc_cx, dy = x(1) - disc_cy;
   return sqrt(dx * dx + dy * dy) - disc_R;
}

// The manufactured solution, with C = I so that u = -grad p.
real_t pExact(const Vector &x) { return sin(x(0)) * sin(x(1)); }

void uExact(const Vector &x, Vector &u)
{
   u(0) = -cos(x(0)) * sin(x(1));
   u(1) = -sin(x(0)) * cos(x(1));
}

/// The source of the potential equation, g = -div u.
real_t gExact(const Vector &x) { return -2.0 * pExact(x); }

/// The datum as the flux equation takes it: negated, as elsewhere on this
/// branch. See HDGExtensionIntegrator on why that fixes the sign of the
/// extension term.
real_t pNatural(const Vector &x) { return -pExact(x); }

struct Result
{
   real_t err_u{}, err_p{};        ///< L2 errors on D_h
   real_t ext_u{}, ext_p{};        ///< and on the complement, normalized
   real_t area_c{};                ///< the measure of D_h^c, as swept
   real_t area_err{};              ///< how far that is from |Omega| - |D_h|
   real_t dist{};        ///< the largest distance from Gamma_h to Gamma
   int    dofs{};        ///< size of the hybridized system
   int    elements{};
   bool   converged{};
};

/// Solve on D_h. With @a extend the Dirichlet datum is transferred from Gamma;
/// otherwise it is read on Gamma_h itself, which is the boundary-fitted
/// problem on the same subdomain and so is the thing to match.
Result Solve(int n, int order, real_t tau, real_t offset, bool level_set_path,
             bool extend, int line_order, bool visualization = false)
{
   const int dim = 2;

   Mesh background = Mesh::MakeCartesian2D(n, n, Element::TRIANGLE);

   Array<int> marker;
   const int inside = MarkLevelSetSubdomain(background, LevelSet, offset,
                                            marker);
   MFEM_VERIFY(inside > 0, "the subdomain is empty; the mesh is too coarse");
   for (int i = 0; i < background.GetNE(); i++)
   {
      background.SetAttribute(i, marker[i] ? 1 : 2);
   }
   background.SetAttributes();

   Array<int> domain_attr(1);
   domain_attr[0] = 1;
   auto D_h = make_unique<SubMesh>(
                 SubMesh::CreateFromDomain(background, domain_attr));

   // D_h lies strictly inside the background mesh, so the whole of its
   // boundary is generated by the extraction and carries the one new
   // attribute: that is Gamma_h.
   MFEM_VERIFY(D_h->bdr_attributes.Size() == 1,
               "an element of D_h touches the boundary of the background mesh");
   const int gamma_h = D_h->bdr_attributes.Max();
   Array<int> bdr_gamma_h(gamma_h);
   bdr_gamma_h = 0;
   bdr_gamma_h[gamma_h - 1] = 1;

   // The paths. The closest-point map is the closed form available for this
   // boundary; the level-set family needs no such form, only the level set
   // that selected the subdomain, and marches along the outward normal.
   Vector centre(2);
   centre(0) = disc_cx; centre(1) = disc_cy;
   unique_ptr<TransferPath> path;
   if (level_set_path)
   {
      path = make_unique<LevelSetPath>(LevelSet, 4.0 / n);
   }
   else
   {
      path = make_unique<ClosestPointPath>(
                ClosestPointPath::Sphere(centre, disc_R));
   }

   L2_FECollection u_coll(order, dim, BasisType::GaussLobatto);
   L2_FECollection p_coll(order, dim);
   FiniteElementSpace fes_u(D_h.get(), &u_coll, dim);
   FiniteElementSpace fes_p(D_h.get(), &p_coll);

   ConstantCoefficient C(1.0);          // the inverse diffusion tensor
   VectorFunctionCoefficient zero(dim, [](const Vector &, Vector &f) { f = 0.0; });
   FunctionCoefficient gcoeff(gExact);
   FunctionCoefficient pcoeff(pExact);
   VectorFunctionCoefficient ucoeff(dim, uExact);

   FunctionCoefficient datum_here(pNatural);
   PathTraceCoefficient datum_there(*path, pNatural);
   Coefficient &datum = extend ? static_cast<Coefficient &>(datum_there)
                        : static_cast<Coefficient &>(datum_here);

   DarcyForm darcy(&fes_u, &fes_p);

   darcy.GetFluxMassForm()->AddDomainIntegrator(new VectorMassIntegrator(C));
   if (extend)
   {
      // The solution-dependent half of the transferred datum. It is local to
      // the element owning the face, so it goes into that element's own flux
      // mass block and the hybridization never sees it.
      darcy.GetFluxMassForm()->AddBdrFaceIntegrator(
         new HDGExtensionIntegrator(*path, C, +1.0, line_order), bdr_gamma_h);
   }

   MixedBilinearForm *B = darcy.GetFluxDivForm();
   B->AddDomainIntegrator(new VectorDivergenceIntegrator());
   B->AddInteriorFaceIntegrator(
      new TransposeIntegrator(new DGNormalTraceIntegrator(-1.0)));

   // HDGDiffusionIntegrator's parameter is tau*h/kappa, not tau. The meshes
   // are uniform on the unit square, so h = 1/n and passing tau/n holds the
   // stabilization fixed under refinement, which is the scaling the reference
   // uses. Holding the parameter itself fixed is a different method: it makes
   // tau grow like 1/h and costs the flux an order.
   darcy.GetPotentialMassForm()->AddInteriorFaceIntegrator(
      new HDGDiffusionIntegrator(C, tau / n));

   LinearForm *fform = darcy.GetFluxRHS();
   fform->AddDomainIntegrator(new VectorDomainLFIntegrator(zero));
   fform->AddBdrFaceIntegrator(new VectorBoundaryFluxLFIntegrator(datum),
                               bdr_gamma_h);
   darcy.GetPotentialRHS()->AddDomainIntegrator(new DomainLFIntegrator(gcoeff));

   Array<int> ess_flux_tdofs;
   DG_Interface_FECollection trace_coll(order, dim);
   FiniteElementSpace fes_t(D_h.get(), &trace_coll);
   darcy.EnableHybridization(&fes_t, new NormalTraceJumpIntegrator(),
                             ess_flux_tdofs);

   darcy.Assemble();

   BlockVector x(darcy.GetOffsets());
   x = 0.0;

   OperatorPtr A;
   Vector X, RHS;
   darcy.FormLinearSystem(ess_flux_tdofs, x, A, X, RHS, true);

   Result res;
   res.dofs = X.Size();
   res.elements = D_h->GetNE();

   GSSmoother prec;
   GMRESSolver solver;
   solver.SetKDim(500);
   solver.SetMaxIter(5000);
   solver.SetRelTol(0.0);
   solver.SetAbsTol(1e-12);
   solver.SetPreconditioner(prec);
   solver.SetOperator(*A);
   solver.Mult(RHS, X);
   res.converged = solver.GetConverged();

   darcy.RecoverFEMSolution(X, x);

   GridFunction u_h, p_h;
   u_h.MakeRef(&fes_u, x.GetBlock(0), 0);
   p_h.MakeRef(&fes_p, x.GetBlock(1), 0);
   res.err_u = u_h.ComputeL2Error(ucoeff);
   res.err_p = p_h.ComputeL2Error(pcoeff);

   // How far the computational boundary stands from the true one, which is the
   // parameter the whole construction is about.
   Vector xp, xbar;
   for (int be = 0; be < D_h->GetNBE(); be++)
   {
      FaceElementTransformations *FTr = D_h->GetBdrFaceTransformations(be);
      if (!FTr) { continue; }
      const IntegrationRule &ir = IntRules.Get(FTr->GetGeometryType(), 4);
      for (int q = 0; q < ir.GetNPoints(); q++)
      {
         path->Endpoint(*FTr, ir.IntPoint(q), xbar);
         FTr->Transform(ir.IntPoint(q), xp);
         xbar -= xp;
         res.dist = max(res.dist, xbar.Norml2());
      }
   }

   // The approximation on D_h^c: the flux is the extension of the element's
   // own polynomial, and the potential is the lifting evaluated there rather
   // than only on Gamma_h. This is the half of the method's claim that is
   // about the whole of Omega.
   {
      const int iro = 2 * order + 8;
      const IntegrationRule &fir = IntRules.Get(Geometry::SEGMENT, iro);
      const IntegrationRule &lir = IntRules.Get(Geometry::SEGMENT, iro);

      IsoparametricTransformation el_tr;
      ElementExtension ext;
      Vector ue(dim), ye(dim), v;
      real_t e2u = 0.0, e2p = 0.0;

      for (int be = 0; be < D_h->GetNBE(); be++)
      {
         FaceElementTransformations *FTr = D_h->GetBdrFaceTransformations(be);
         if (!FTr) { continue; }

         const int el = FTr->Elem1No;
         D_h->GetElementTransformation(el, &el_tr);
         ext.SetElement(el_tr);

         auto Cu = [&](const Vector &yy, Vector &vv)
         {
            IntegrationPoint eip;
            MFEM_VERIFY(ext.TransformBack(yy, eip), "no convergence");
            u_h.GetVectorValue(el, eip, vv);
         };

         ExtensionRegionQuadrature(
            *FTr, *path, fir, lir, [&](const ExtensionPoint &pt)
         {
            uExact(pt.y, ue);
            Cu(pt.y, v);
            real_t du = 0.0;
            for (int d = 0; d < dim; d++)
            {
               const real_t s = ue(d) - v(d);
               du += s * s;
            }
            // The lifting from the point itself, not from Gamma_h.
            const real_t lift =
               pExact(pt.xbar) + PathIntegral(Cu, pt.y, pt.xbar, lir);
            const real_t dp = pExact(pt.y) - lift;

            e2u += pt.weight * du;
            e2p += pt.weight * dp * dp;
            res.area_c += pt.weight;
         });
      }

      real_t vol_D = 0.0;
      for (int i = 0; i < D_h->GetNE(); i++) { vol_D += D_h->GetElementVolume(i); }
      const real_t vol_c = M_PI * disc_R * disc_R - vol_D;
      res.area_err = fabs(res.area_c - vol_c) / vol_c;

      // Normalized by the measure of the region, as the reference does: it
      // shrinks like h, and a raw L2 norm over it would carry half an order
      // that has nothing to do with the approximation.
      const real_t s = (res.area_c > 0.0) ? sqrt(res.area_c) : 1.0;
      res.ext_u = sqrt(e2u) / s;
      res.ext_p = sqrt(e2p) / s;
   }

   if (visualization)
   {
      // The subdomain and the solution on it. The region between Gamma_h and
      // Gamma is not meshed and so is not drawn; what is drawn stops where the
      // extension takes over.
      char vishost[] = "localhost";
      const int visport = 19916;
      socketstream sol_sock(vishost, visport);
      if (sol_sock.is_open())
      {
         sol_sock.precision(8);
         sol_sock << "solution\n" << *D_h << p_h
                  << "window_title 'potential on D_h'\n" << flush;
      }
      else
      {
         cout << "Unable to connect to GLVis server at "
              << vishost << ':' << visport << endl;
      }
   }

   return res;
}

} // namespace

int main(int argc, char *argv[])
{
   int order = 1;
   int n = 8;
   int refinements = 3;
   int line_order = -1;
   real_t tau = 1.0;
   real_t offset = 0.0;
   const char *path_type = "cp";
   bool extend = true;
   bool control = true;
   bool visualization = true;

   OptionsParser args(argc, argv);
   args.AddOption(&order, "-o", "--order",
                  "Polynomial degree of the flux, potential and trace.");
   args.AddOption(&n, "-n", "--num-divisions",
                  "Divisions per side of the coarsest background mesh.");
   args.AddOption(&refinements, "-r", "--refinements",
                  "Halvings of the background mesh size after the first.");
   args.AddOption(&tau, "-tau", "--stabilization",
                  "The HDG stabilization, held fixed under refinement.");
   args.AddOption(&offset, "-d", "--offset",
                  "Select against phi <= -offset, pushing Gamma_h further "
                  "from Gamma. Zero takes every element that fits.");
   args.AddOption(&disc_R, "-R", "--radius", "Radius of the disc.");
   args.AddOption(&path_type, "-path", "--path-family",
                  "'cp' for the closest-point map, 'ls' for a normal ray "
                  "bisected on the level set.");
   args.AddOption(&line_order, "-lo", "--line-order",
                  "Order of the quadrature along the paths; negative takes "
                  "twice the element order plus two.");
   args.AddOption(&extend, "-ext", "--extend", "-no-ext", "--no-extend",
                  "Transfer the datum from Gamma. Without it the datum is "
                  "read on Gamma_h itself, which is a different problem.");
   args.AddOption(&visualization, "-vis", "--visualization", "-no-vis",
                  "--no-visualization",
                  "Send the potential on the finest D_h to GLVis.");
   args.AddOption(&control, "-ctl", "--control", "-no-ctl", "--no-control",
                  "Also solve with the datum read on Gamma_h and report the "
                  "ratio of the errors.");
   args.Parse();
   if (!args.Good()) { args.PrintUsage(cout); return 1; }
   args.PrintOptions(cout);

   const bool level_set_path = (string(path_type) == "ls");
   MFEM_VERIFY(level_set_path || string(path_type) == "cp",
               "unknown path family '" << path_type << "'");

   cout << "\n"
        << "The errors on D_h are plain L2 norms; those on its complement are\n"
        << "divided by the square root of its measure, which shrinks like h.\n\n"
        << "   n    elem     dofs      dist       ||u-u_h||   rate"
        << "     ||p-p_h||   rate      ext_u      rate      ext_p      rate";
   if (control && extend) { cout << "    ratio_u  ratio_p"; }
   cout << "\n";

   auto column = [](real_t err, real_t prev)
   {
      cout << "   " << scientific << setprecision(4) << err << "  " << fixed
           << setw(5) << setprecision(2) << (prev > 0.0 ? log2(prev / err) : 0.0);
   };

   real_t prev_u = 0.0, prev_p = 0.0, prev_xu = 0.0, prev_xp = 0.0;
   real_t worst_area = 0.0;
   int nn = n;
   for (int r = 0; r <= refinements; r++)
   {
      const Result e = Solve(nn, order, tau, offset, level_set_path, extend,
                             line_order, visualization && r == refinements);

      cout << setw(4) << nn << setw(8) << e.elements << setw(9) << e.dofs
           << "  " << scientific << setprecision(2) << e.dist;
      column(e.err_u, prev_u);
      column(e.err_p, prev_p);
      column(e.ext_u, prev_xu);
      column(e.ext_p, prev_xp);

      if (control && extend)
      {
         const Result c = Solve(nn, order, tau, offset, level_set_path, false,
                                line_order);
         cout << "  " << setw(7) << setprecision(3) << e.err_u / c.err_u
              << "  " << setw(7) << e.err_p / c.err_p;
         if (!c.converged) { cout << "  [control did not converge]"; }
      }
      if (!e.converged) { cout << "  [NOT CONVERGED]"; }
      cout << "\n";

      worst_area = max(worst_area, e.area_err);
      prev_u = e.err_u;
      prev_p = e.err_p;
      prev_xu = e.ext_u;
      prev_xp = e.ext_p;
      nn *= 2;
   }

   // The regions swept by the paths must tile the complement exactly, or the
   // two columns above are integrals over the wrong set. The closest-point map
   // tiles; a family following each face's own normal does not, adjacent faces
   // disagreeing on the path through the vertex they share.
   cout << "\nlargest relative error in the measure of D_h^c: "
        << scientific << setprecision(2) << worst_area << "\n";
   if (worst_area > 1e-6)
   {
      cout << "the extension regions do not tile the complement, so the two "
           "columns above\nare not integrals over it\n";
   }
   cout << endl;

   return 0;
}
