#!/bin/sh

# Copyright (c) 2010, Lawrence Livermore National Security, LLC. Produced at the
# Lawrence Livermore National Laboratory. LLNL-CODE-443211. All Rights reserved.
# See file COPYRIGHT for details.
#
# This file is part of the MFEM library. For more information and source code
# availability see http://mfem.googlecode.com.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.

# Echo usage information
case $1 in
   -h|-help)
      cat <<EOF

   $0 [-h|-help] {mfem_dir}

   where: {mfem_dir}  is the MFEM source directory [default value: ../mfem]
          -h|-help    prints this usage information and exits

   This script tests all the sample runs listed in the begining comments of
   MFEM's parallel example codes. The list was generated and should be
   periodically updated with the grep commands below.

   Example usage: $0 ../..

EOF
      exit
      ;;
esac

# Setup
mfem_dir=$1
if [ "$mfem_dir" = "" ]; then
    mfem_dir="../.."
fi
shift
cd $mfem_dir
mfem_dir=`pwd`

# Make sure parallel examples are built
cd $mfem_dir
( make distclean; make parallel -j
  cd examples; make -j ) > /dev/null 2>&1

# The list below was obtained with: grep -E "ex[0-9][0-9]?p " ex*p.cpp
cd $mfem_dir/examples
mpirun -np 13 ex1p  -h
mpirun -np 13 ex1p  -no-vis
mpirun -np 13 ex1p  -no-vis -m ../data/square-disc.mesh
mpirun -np 13 ex1p  -no-vis -m ../data/star.mesh
mpirun -np 13 ex1p  -no-vis -m ../data/escher.mesh
mpirun -np 13 ex1p  -no-vis -m ../data/fichera.mesh
mpirun -np 13 ex1p  -no-vis -m ../data/square-disc-p2.vtk -o 2
mpirun -np 13 ex1p  -no-vis -m ../data/square-disc-p3.mesh -o 3
mpirun -np 13 ex1p  -no-vis -m ../data/square-disc-nurbs.mesh -o -1
mpirun -np 13 ex1p  -no-vis -m ../data/disc-nurbs.mesh -o -1
mpirun -np 13 ex1p  -no-vis -m ../data/pipe-nurbs.mesh -o -1
mpirun -np 13 ex1p  -no-vis -m ../data/ball-nurbs.mesh -o 2
mpirun -np 13 ex1p  -no-vis -m ../data/star-surf.mesh
mpirun -np 13 ex1p  -no-vis -m ../data/square-disc-surf.mesh
mpirun -np 13 ex1p  -no-vis -m ../data/inline-segment.mesh
mpirun -np 13 ex2p  -h
mpirun -np 13 ex2p  -no-vis
mpirun -np 13 ex2p  -no-vis -m ../data/beam-tri.mesh
mpirun -np 13 ex2p  -no-vis -m ../data/beam-quad.mesh
mpirun -np 13 ex2p  -no-vis -m ../data/beam-tet.mesh
mpirun -np 13 ex2p  -no-vis -m ../data/beam-hex.mesh
mpirun -np 13 ex2p  -no-vis -m ../data/beam-quad-nurbs.mesh
mpirun -np 13 ex2p  -no-vis -m ../data/beam-hex-nurbs.mesh
mpirun -np 13 ex3p  -h
mpirun -np 13 ex3p  -no-vis
mpirun -np 13 ex3p  -no-vis -m ../data/beam-tet.mesh
mpirun -np 13 ex3p  -no-vis -m ../data/beam-hex.mesh
mpirun -np 13 ex3p  -no-vis -m ../data/escher.mesh
mpirun -np 13 ex3p  -no-vis -m ../data/fichera.mesh
mpirun -np 13 ex3p  -no-vis -m ../data/fichera-q2.vtk
mpirun -np 13 ex3p  -no-vis -m ../data/fichera-q3.mesh
mpirun -np 13 ex3p  -no-vis -m ../data/beam-hex-nurbs.mesh
mpirun -np 13 ex4p  -h
mpirun -np 13 ex4p  -no-vis
mpirun -np 13 ex4p  -no-vis -m ../data/square-disc.mesh
mpirun -np 13 ex4p  -no-vis -m ../data/star.mesh
mpirun -np 13 ex4p  -no-vis -m ../data/beam-tet.mesh
mpirun -np 13 ex4p  -no-vis -m ../data/beam-hex.mesh
mpirun -np 13 ex4p  -no-vis -m ../data/escher.mesh
mpirun -np 13 ex4p  -no-vis -m ../data/fichera.mesh
mpirun -np 13 ex4p  -no-vis -m ../data/fichera-q2.vtk
mpirun -np 13 ex4p  -no-vis -m ../data/fichera-q3.mesh
mpirun -np 13 ex4p  -no-vis -m ../data/square-disc-nurbs.mesh
mpirun -np 13 ex4p  -no-vis -m ../data/beam-hex-nurbs.mesh
mpirun -np 13 ex4p  -no-vis -m ../data/periodic-square.mesh -no-bc
mpirun -np 13 ex4p  -no-vis -m ../data/periodic-cube.mesh -no-bc
mpirun -np 13 ex5p  -h
mpirun -np 13 ex5p  -no-vis
mpirun -np 13 ex5p  -no-vis -m ../data/square-disc.mesh
mpirun -np 13 ex5p  -no-vis -m ../data/star.mesh
mpirun -np 13 ex5p  -no-vis -m ../data/beam-tet.mesh
mpirun -np 13 ex5p  -no-vis -m ../data/beam-hex.mesh
mpirun -np 13 ex5p  -no-vis -m ../data/escher.mesh
mpirun -np 13 ex5p  -no-vis -m ../data/fichera.mesh
mpirun -np 13 ex7p  -h
mpirun -np 13 ex7p  -no-vis
mpirun -np 13 ex7p  -no-vis -e 0 -o 2 -r 4
mpirun -np 13 ex7p  -no-vis -e 1 -o 2 -r 4 -snap
mpirun -np 13 ex8p  -h
mpirun -np 13 ex8p  -no-vis
mpirun -np 13 ex8p  -no-vis -m ../data/square-disc.mesh
mpirun -np 13 ex8p  -no-vis -m ../data/star.mesh
mpirun -np 13 ex8p  -no-vis -m ../data/escher.mesh
mpirun -np 13 ex8p  -no-vis -m ../data/fichera.mesh
mpirun -np 13 ex8p  -no-vis -m ../data/square-disc-p2.vtk
mpirun -np 13 ex8p  -no-vis -m ../data/square-disc-p3.mesh
mpirun -np 13 ex8p  -no-vis -m ../data/star-surf.mesh -o 2
mpirun -np 13 ex9p  -h
mpirun -np 13 ex9p  -no-vis
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-segment.mesh -p 0 -rs 2 -rp 0 -dt 0.005
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-square.mesh -p 0 -rs 2 -rp 0 -dt 0.01 -tf 10
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-hexagon.mesh -p 0 -rs 2 -rp 0 -dt 0.01 -tf 10
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-square.mesh -p 1 -rs 2 -rp 0 -dt 0.005 -tf 9
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-hexagon.mesh -p 1 -rs 2 -rp 0 -dt 0.005 -tf 9
mpirun -np 13 ex9p  -no-vis -m ../data/disc-nurbs.mesh -p 2 -rs 2 -rp 1 -dt 0.005 -tf 9
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-square.mesh -p 3 -rs 2 -rp 2 -dt 0.0025 -tf 9 -vs 20
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-cube.mesh -p 0 -o 2 -rs 2 -rp 1 -dt 0.01 -tf 8
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-segment.mesh -p 0 -r 2 -dt 0.005
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-square.mesh -p 0 -r 2 -dt 0.01 -tf 10
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-hexagon.mesh -p 0 -r 2 -dt 0.01 -tf 10
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-square.mesh -p 1 -r 2 -dt 0.005 -tf 9
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-hexagon.mesh -p 1 -r 2 -dt 0.005 -tf 9
mpirun -np 13 ex9p  -no-vis -m ../data/disc-nurbs.mesh -p 2 -r 3 -dt 0.005 -tf 9
mpirun -np 13 ex9p  -no-vis -m ../data/periodic-square.mesh -p 3 -r 4 -dt 0.0025 -tf 9 -vs 20
mpirun -np 13 ex10p -h
mpirun -np 13 ex10p -no-vis
mpirun -np 13 ex10p -no-vis -m ../data/beam-quad.mesh -s 3 -rs 2 -rp 0 -o 2 -dt 3
mpirun -np 13 ex10p -no-vis -m ../data/beam-tri.mesh -s 3 -rs 2 -rp 0 -o 2 -dt 3
mpirun -np 13 ex10p -no-vis -m ../data/beam-hex.mesh -s 2 -rs 1 -rp 0 -o 2 -dt 3
mpirun -np 13 ex10p -no-vis -m ../data/beam-tet.mesh -s 2 -rs 1 -rp 0 -o 2 -dt 3
mpirun -np 13 ex10p -no-vis -m ../data/beam-quad.mesh -s 14 -rs 2 -rp 0 -o 2 -dt 0.03 -vs 20
mpirun -np 13 ex10p -no-vis -m ../data/beam-hex.mesh -s 14 -rs 1 -rp 0 -o 2 -dt 0.05 -vs 20

cd ..
