# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: install-metis

inputs:
  metis-url:
    description: 'URL where to look for Metis'
    required: false
    default: 'https://mfem.github.io/tpls'
  metis-archive:
    description: 'Archive to download'
    required: true
  metis-dir:
    description: 'Metis top directory name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Metis
      run: |
        wget --no-verbose ${{ inputs.metis-url }}/${{ inputs.metis-archive }};
        rm -rf ${{ inputs.metis-dir }};
        tar -xzf ${{ inputs.metis-archive }};
        make -j3 -C ${{ inputs.metis-dir }}/Lib CC=mpicc OPTFLAGS="-Wno-error=implicit-function-declaration -O2";
      shell: bash
