# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: install-hypre

inputs:
  url:
    description: 'URL where to look for Hypre'
    required: false
    default: 'https://github.com/hypre-space/hypre/archive'
  archive:
    description: 'Archive to download'
    required: true
  dir:
    description: 'Hypre top directory name'
    required: true
  target:
    description: 'A key to identify desired hypre config'
    required: true

runs:
  using: "composite"
  steps:
    - name: Map target to options
      run: |
        if [[ ${{ inputs.target }} == "basic" ]]
        then
          export hypre_options="--disable-fortran"
        elif [[ ${{ inputs.target }} == "bigint" ]]
        then
          export hypre_options="--disable-fortran --enable-bigint"
        else
          echo "Hypre target not recognized"
          exit 1
        fi

    - name: Install Hypre
      run: |
        wget --no-verbose ${{ inputs.url }}/${{ inputs.archive }};
        rm -rf ${{ inputs.dir }};
        tar -xzf ${{ inputs.archive }};
        cd ${{ inputs.dir }}/src;
        ./configure ${hypre_options} CC=mpicc CXX=mpic++;
        make -j3;
        cd ../..;
      shell: bash
