# Copyright (c) 2010-2021, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.

name: install-hypre

inputs:
  hypre-url:
    description: 'URL where to look for Hypre'
    required: false
    default: 'https://github.com/hypre-space/hypre/archive'
  hypre-archive:
    description: 'Archive to download'
    required: true
  hypre-dir:
    description: 'Hypre top directory name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Hypre
      run: |
        wget --no-verbose ${{ inputs.hypre-url }}/${{ inputs.hypre-archive }};
        rm -rf ${{ inputs.hypre-dir }};
        tar -xzf ${{ inputs.hypre-archive }};
        cd ${{ inputs.hypre-dir }}/src;
        ./configure --disable-fortran CC=mpicc CXX=mpic++;
        make -j3;
        cd ../..;
      shell: bash
