/**
 * @file CCSA_Bregman_MFEM.hpp
 * @brief Device-aware CCSA optimiser for MFEM using a Fermi-Dirac Bregman
 *        separable approximation, with a latent (logit) primal variable.
 *
 * This declares mfem_mma::CCSAOptimizer / mfem_mma::CCSAOptimizerParallel:
 * a Conservative Convex Separable Approximation (CCSA) optimiser whose
 * subproblem model is the separable approximation generated by the Bregman
 * divergence of the negative binary Fermi-Dirac entropy, rather than MMA's
 * rational (reciprocal-asymptote) model. See the accompanying technical note
 * "A Fermi-Dirac Bregman Separable Approximation for CCSA/MMA" (referred to
 * below as [Note]) for the full derivation; section numbers quoted in
 * comments below refer to that note.
 *
 * @section relationship Relationship to MMA_MFEM.hpp / MMA_MFEM.cpp
 *
 * This header/source pair is kept SEPARATE from MMA_MFEM.hpp/.cpp in this
 * initial phase (they are not modified), but deliberately shares as much as
 * is safe to share across a translation-unit boundary:
 *   - Same namespace: everything below lives in @c mfem_mma, alongside
 *     @c MMAOptimizer / @c SQOptimizer.
 *   - This header @c \#include's MMA_MFEM.hpp and reuses its
 *     @c PackFival() / @c PackFivalRelaxed() / @c PackedDfidx (equality-
 *     constraint helpers) and @c detail::SolveDense() (the dense m x m
 *     solver used by the BarrierNewton dual solver below) directly --
 *     neither is redeclared or redefined here.
 *   - A handful of small helpers declared @c static (i.e. internal linkage)
 *     in MMA_MFEM.cpp -- the MPI-reduction wrapper, its serial-comm
 *     sentinel, and three penalty/bookkeeping helpers -- are NOT reachable
 *     from CCSA_Bregman_MFEM.cpp and are therefore duplicated there under
 *     @c ccsa_-prefixed names. See the top of CCSA_Bregman_MFEM.cpp for the
 *     precise list; that duplication is the only thing a future merge into
 *     MMA_MFEM.hpp/.cpp would remove.
 *   - Link CCSA_Bregman_MFEM.cpp together with MMA_MFEM.cpp (the former
 *     calls @c mfem_mma::detail::SolveDense(), defined in the latter).
 *
 * @section why Why this exists (differences from MMA/GCMMA)
 *
 *   - @b No asymptotes.  MMA/GCMMA re-derives moving asymptotes L, U from
 *     the iterate history every outer step (Svanberg 2007 eq. 3.11-3.14).
 *     Here the "moving bounds" ell, u ([Note] Sec. 2) are set once (via a
 *     BoundsGeometry object, see below) and stay fixed for the rest of the
 *     optimisation, until the user explicitly resets them.
 *
 *   - @b Latent primal state.  The optimiser works directly on a latent
 *     (logit-type) vector eta ([Note] Sec. 8) rather than the physical
 *     design x -- see @ref latent below for the full contract. The
 *     physical x is recovered from eta by a fixed, bound-specific sigmoid
 *     map that guarantees x stays strictly inside the bounds at every
 *     iteration, by construction, with no clipping.
 *
 *   - @b Bounds geometry is a separate, exchangeable object (BoundsGeometry
 *     and its factories TwoSided/LowerOnly/UpperOnly).  Two-sided bounds use
 *     the Fermi-Dirac (logit/sigmoid) map; one-sided bounds use the
 *     analogous unnormalised Boltzmann-Shannon entropy (log/exp map).  Both
 *     share the same closed-form fixed-dual latent update (eq. 48/91/98 in
 *     [Note]), so the rest of the optimiser is agnostic to which is used.
 *
 *   - @b Pluggable dual solver.  The m-dimensional dual sub-problem (fixed
 *     rho, solve for the Lagrange multipliers lambda) is implemented as a
 *     free function in detail::, exactly like detail::SolveDualIP in
 *     MMA_MFEM.hpp, and is selected at runtime via DualSolverKind:
 *       - @c ProjectedAscent : simple projected dual-ascent (Sec. 6.7).  No
 *         global-convergence guarantee for m > 1 in general, but robust and
 *         cheap.  This is the default, and the solver you get "out of the
 *         box".
 *       - @c BarrierNewton   : primal-dual barrier Newton method (Sec. 6.8),
 *         mirroring the architecture of detail::SolveDualIP.  Locally fast;
 *         recommended once the projected-ascent solver has been validated
 *         on your problem.
 *
 *   - @b Outer loop.  Exactly like MMAOptimizer, Update() is the plain
 *     (non-globally-convergent) CCSA step (single rho, no conservatism
 *     check) and UpdateGCMMA() is the globally-convergent step that
 *     increases rho until the model is conservative at the trial point
 *     (Svanberg 2002; [Note] Sec. 5.1).  UpdateGCMMA()'s rho update rule is
 *     currently the same "increase-on-violation" rule used by
 *     MMAOptimizer::UpdateGCMMA().  A natural extension point,
 *     ComputeInitialRho_(), is provided (protected, virtual) for a future
 *     Barzilai-Borwein step-size estimate in the style of the SiMPL method
 *     (Kim, Lazarov, Surowiec & Keith 2025) -- see the comment on that
 *     method below.
 *
 * @section dropin Relationship to the MMA/SQ "drop-in" surface
 *
 * CCSAOptimizer / CCSAOptimizerParallel share constructors' penalty-argument
 * shape, WithEqualities()/WithRelaxedEqualities(), KKTresidual()'s general
 * contract, GetLambda(), GetIteration()/NumIterations(),
 * NumEqualities()/NumInequalities()/NumConstraints() with
 * MMAOptimizer/SQOptimizer -- but Update()/UpdateGCMMA()/KKTresidual()
 * themselves are deliberately NOT drop-in: they operate on the LATENT
 * variable eta, not the physical design x (see @ref latent below), and take
 * no xmin/xmax at all. PackFival(), PackFivalRelaxed() and PackedDfidx --
 * declared in MMA_MFEM.hpp and included transitively here -- still work
 * unchanged for the fival/dfidx arguments.
 *
 * Two MMAOptimizer/SQOptimizer methods are not reproduced, because they
 * encode concepts that do not exist here: SetAsymptotes() (no asymptotes)
 * and SetSigmaScale() (no per-iteration sigma; use the bounds' fixed
 * Scale() instead, see BoundsGeometry).
 *
 * @section latent Working on the latent variable eta
 *
 * Unlike MMAOptimizer (which takes and returns the physical design x),
 * CCSAOptimizer's Update()/UpdateGCMMA()/KKTresidual() take and return the
 * LATENT variable eta directly: the @p x parameter of these methods IS
 * eta, in/out. There is no internal "current state" stored by the
 * optimiser itself -- exactly as MMAOptimizer does not store its own copy
 * of the physical x, CCSAOptimizer does not store its own copy of eta;
 * whichever mfem::Vector the caller passes to Update() is the state.
 *
 * Consequences:
 *   - A BoundsGeometry MUST be established before the first Update() call,
 *     either via a constructor that takes one or via SetBounds(). There is
 *     no more auto-detection from xmin/xmax (contrast with the drop-in
 *     design this superseded): Update()/UpdateGCMMA()/KKTresidual() throw
 *     if HasBounds() is false.
 *   - Converting between the physical design and eta is the caller's
 *     responsibility, using ToLatent() (physical -> latent, e.g. to seed
 *     the initial eta from an initial physical guess x0) and ToPhysical()
 *     (latent -> physical, e.g. before evaluating the objective/constraint
 *     functions and their gradients, which are naturally physical-space
 *     quantities such as FEM sensitivities).
 *   - df0dx/dfidx passed to Update()/UpdateGCMMA()/KKTresidual() are still
 *     physical-space gradients (df0/dx_j, dfi/dx_j) evaluated at
 *     ToPhysical(eta); nothing changes there. The EvalCallback passed to
 *     the full UpdateGCMMA() overload is likewise still called with a
 *     PHYSICAL trial point, since that is what the user's evaluator needs.
 *
 * Typical usage:
 * @code
 *   auto bounds = mfem_mma::BoundsGeometry::TwoSided(xmin, xmax);
 *   CCSAOptimizer opt(n, m, bounds);
 *   mfem::Vector eta = opt.ToLatent(x0);        // seed from an initial guess
 *   for (int k = 0; k < max_iter; ++k) {
 *       mfem::Vector x = opt.ToPhysical(eta);   // physical view for evaluation
 *       ComputeObjectiveAndGradients(x, f0, df0, fi, dfi);
 *       opt.Update(eta, df0, f0, fi, dfi.data());       // eta updated in place
 *       x = opt.ToPhysical(eta);
 *       ComputeObjectiveAndGradients(x, f0, df0, fi, dfi);
 *       if (opt.KKTresidual(eta, df0, f0, fi, dfi.data()) < tol) break;
 *   }
 *   mfem::Vector x_final = opt.ToPhysical(eta);
 * @endcode
 *
 * KKTresidual()'s formula also changes as a consequence: since eta ranges
 * freely over all of R^n by construction (the box constraint is absorbed
 * entirely into the ToPhysical() map), there is no boundary left to project
 * the Lagrangian gradient against. The old physical-space "projected
 * gradient" check is replaced by a plain chain-rule stationarity check in
 * eta-space, dL/deta_j = (dL/dx_j) * (dx_j/deta_j); the factor dx_j/deta_j
 * (= h_j * kappa_j, the same curvature factor used by the BarrierNewton
 * dual solver) naturally -> 0 as x_j saturates a bound, which is exactly
 * what the old explicit projection achieved by hand.
 *
 * @section device Device execution
 *
 * Same strategy as MMA_MFEM.hpp: all O(n) work (bounds maps, per-iteration
 * primal updates, Bregman-divergence reductions) runs via
 * mfem::forall_switch / mfem::Vector::Sum() / mfem::InnerProduct on
 * whichever device x lives on; the m x m (or m) dual system is always
 * assembled and solved on the host.
 *
 * @section refs References
 *   - K. Svanberg (2002), A class of globally convergent optimization
 *     methods based on conservative convex separable approximations,
 *     SIAM J. Optim. 12(2):555-573.
 *   - K. Svanberg (2007), MMA and GCMMA - two methods for nonlinear
 *     optimization, KTH Tech Note.
 *   - N. Aage, B.S. Lazarov (2013), Parallel framework for topology
 *     optimization using MMA, Struct Multidisc Optim 47:493-505.
 *   - D. Kim, B.S. Lazarov, T.M. Surowiec, B. Keith (2025), A simple
 *     introduction to the SiMPL method for density-based topology
 *     optimization, Struct Multidisc Optim 68:74.
 *   - [Note] "A Fermi-Dirac Bregman Separable Approximation for CCSA/MMA",
 *     technical note, 2026 (uploaded project file CCSA_Bregman.pdf).
 */

#pragma once

#include "MMA_MFEM.hpp"

namespace mfem_mma {

// CCSAOptimizer / CCSAOptimizerParallel -- Fermi-Dirac Bregman CCSA.
// See the file-level doc comment above for an overview (particularly
// @ref relationship and @ref why). Shares the mfem_mma namespace,
// PackFival()/PackFivalRelaxed()/PackedDfidx, and detail::SolveDense() with
// MMAOptimizer/SQOptimizer (declared in MMA_MFEM.hpp, included above);
// nothing here is duplicated from them.
// ============================================================

/**
 * @brief Which asymmetric-bound geometry a coordinate uses (CCSAOptimizer).
 *
 * All three kinds share the same closed-form fixed-dual latent update
 * eta_j(lambda) = eta_c_j - h_j * C_j(lambda) / R(lambda); they differ only
 * in the map between eta_j and the physical x_j, and in the local curvature
 * factor kappa_j used by the barrier-Newton dual solver ([Note] Sec. 10.4,
 * and the one-sided generalisation derived for this header).
 *
 *   - TwoSided:  ell_j < x_j < u_j.        eta = logit((x-ell)/h),  h = u-ell.
 *                kappa_j = p_j(1-p_j),     p_j = sigmoid(eta_j).
 *   - LowerOnly: x_j > ell_j (no upper).   eta = log((x-ell)/h),    h = user scale.
 *                kappa_j = p_j,            p_j = exp(eta_j).
 *   - UpperOnly: x_j < u_j (no lower).     eta = -log((u-x)/h),     h = user scale.
 *                kappa_j = p_j,            p_j = exp(-eta_j).
 */
enum class BoundsKind { TwoSided, LowerOnly, UpperOnly };

/**
 * @brief Which numerical strategy solves CCSAOptimizer's m-dimensional dual
 * sub-problem. See @ref why in the file header for a summary.
 */
enum class DualSolverKind { ProjectedAscent, BarrierNewton };

// ============================================================
/**
 * @class BoundsGeometry
 * @brief The "shape" of the constraint set CCSAOptimizer's latent variable
 * maps onto.
 *
 * A BoundsGeometry is a lightweight, copyable, device-aware value type
 * that owns the per-coordinate lower/upper bound (or bound+scale) Vectors
 * and knows how to map between the physical design x and the latent
 * variable eta.  It is completely decoupled from CCSAOptimizer: build one,
 * hand it to the optimiser's constructor or SetBounds(), and it can be
 * swapped out at any time (e.g. to go from two-sided to one-sided bounds,
 * or to reset the bound values) without touching anything else.
 *
 * All ToLatent()/ToPhysical() calls are device-aware: they run through
 * mfem::forall_switch on whichever device the input Vector lives on.
 *
 * @note ToLatent() is exact only in the open interior of the geometry
 * (ell < x < u for TwoSided, x > ell for LowerOnly, x < u for UpperOnly).
 * Physical points supplied to ToLatent() are clipped to
 * [eps, 1-eps] (TwoSided) or [eps, +inf) (one-sided) in normalised
 * coordinates first, see SetClip().
 */
class BoundsGeometry {
public:
    BoundsGeometry() = default;

    /** @brief Two-sided bounds ell_j < x_j < u_j (per-coordinate). */
    static BoundsGeometry TwoSided(const mfem::Vector& lo, const mfem::Vector& hi);
    /** @brief Two-sided bounds, identical scalar bound for all n coordinates. */
    static BoundsGeometry TwoSided(int n, mfem::real_t lo, mfem::real_t hi,
                                    bool use_device = false);

    /**
     * @brief Lower-bound-only geometry x_j > lo_j (per-coordinate).
     * @param scale  Reference width h_j > 0 used in the log/exp map and in
     *               the fixed-dual latent update.  Larger scale means a
     *               given dual gradient produces a larger step in x near
     *               the anchor point; a natural default is a fraction of
     *               a typical/expected variable magnitude.  There is no
     *               upper bound analogous to (u-ell) to derive this from
     *               automatically, so the user must supply it.
     */
    static BoundsGeometry LowerOnly(const mfem::Vector& lo, const mfem::Vector& scale);
    static BoundsGeometry LowerOnly(int n, mfem::real_t lo, mfem::real_t scale,
                                     bool use_device = false);

    /** @brief Upper-bound-only geometry x_j < hi_j (per-coordinate). */
    static BoundsGeometry UpperOnly(const mfem::Vector& hi, const mfem::Vector& scale);
    static BoundsGeometry UpperOnly(int n, mfem::real_t hi, mfem::real_t scale,
                                      bool use_device = false);

    int Size() const { return n_; }
    BoundsKind Kind() const { return kind_; }
    const mfem::Vector& Lo() const { return lo_; }     ///< valid for TwoSided, LowerOnly
    const mfem::Vector& Hi() const { return hi_; }     ///< valid for TwoSided, UpperOnly
    const mfem::Vector& Scale() const { return h_; }   ///< h_j = (u-ell) or user scale

    /// @brief Clip margin used for numerical safety near open-interval edges.
    /// Default 1e-10 in normalised coordinates ([Note] Sec. 4.3 / Sec. 11 item 4).
    void SetClip(mfem::real_t eps) { clip_eps_ = eps; }
    mfem::real_t GetClip() const { return clip_eps_; }

    /// @brief Physical -> latent.  eta must already be sized to x.Size().
    void ToLatent(const mfem::Vector& x, mfem::Vector& eta) const;
    /// @brief Latent -> physical.  x must already be sized to eta.Size().
    void ToPhysical(const mfem::Vector& eta, mfem::Vector& x) const;

    mfem::Vector ToLatent(const mfem::Vector& x) const
    { mfem::Vector eta(x.Size()); eta.UseDevice(x.UseDevice()); ToLatent(x,eta); return eta; }
    mfem::Vector ToPhysical(const mfem::Vector& eta) const
    { mfem::Vector x(eta.Size()); x.UseDevice(eta.UseDevice()); ToPhysical(eta,x); return x; }

    bool IsSet() const { return set_; }

private:
    int n_ = 0;
    bool set_ = false;   ///< true once a factory method has run; n_==0 alone
                          ///< is NOT "unconfigured" -- it's the legitimate
                          ///< zero-DOF-rank case in MPI-parallel use.
    BoundsKind kind_ = BoundsKind::TwoSided;
    mfem::Vector lo_, hi_, h_;
    mfem::real_t clip_eps_ = mfem::real_t(1e-10);
};


// ============================================================
// Additional detail:: helper for the CCSA dual sub-problem.  Reopens the
// detail namespace declared near the top of this file; SolveDense() (used
// by the BarrierNewton solver below) is already declared there.
// ============================================================
namespace detail {

/**
 * @brief Solve the m-dimensional dual sub-problem of the entropy-CCSA model
 * (Bregman separable approximation), for one fixed vector of conservatism
 * weights rho.
 *
 * This is the single, pluggable entry point mentioned in @ref why in the
 * file header: @p kind selects which numerical strategy is used ([Note]
 * Sec. 6.7 ProjectedAscent, Sec. 6.8 BarrierNewton) while every other
 * argument (the model data) is identical between the two.  Reuses
 * detail::SolveDense() (declared in MMA_MFEM.hpp, included above) for the
 * BarrierNewton Newton solve.
 *
 * All O(n_loc) work runs through mfem::forall_switch(use_dev, ...) on the
 * same device as the caller's Vectors. The m (or m x m) dual system is
 * always assembled/solved on the host.  Global (cross-rank) reductions use
 * @p comm; pass the sentinel used by the serial optimiser classes for
 * single-process use (see the .cpp file), exactly as SolveDualIP does.
 *
 * @param kind        Dual-solve strategy.
 * @param comm        MPI communicator (serial sentinel for single-process).
 * @param n_loc       Local number of design variables.
 * @param m           Number of constraints (may be 0: closed-form primal,
 *                     no dual iteration).
 * @param n_eq        Number of encoded equality pairs (trailing 2*n_eq of
 *                     the m slots), same ±h encoding as MMA_MFEM.hpp's PackFival().
 * @param use_dev     Run device kernels when true.
 * @param bounds      Bounds geometry (fixed for the whole optimisation).
 * @param eta_c_loc   Current latent center eta^k (device ptr, length n_loc).
 * @param b0_loc      Objective gradient df0/dx at x^k (device Vector).
 * @param bi_loc      Constraint gradients dfi/dx at x^k, i=1..m (device Vectors).
 * @param F           [f0(x^k), f1(x^k), ..., fm(x^k)] (host, length m+1).
 * @param rho         Conservatism weights [rho_0, ..., rho_m] (host, length m+1).
 * @param a_pen,c_pen,d_pen  CCSA penalty parameters (host, length m), same
 *                     meaning as in MMAOptimizer.
 * @param lam         Dual variable lambda (host, length m). Warm-started on
 *                     entry, updated in place.
 * @param mu          Barrier auxiliary variable (host, length m). Only used
 *                     / updated by BarrierNewton; ignored by ProjectedAscent.
 * @param y           Elastic slack y (host, length m). Written on exit.
 * @param z           Scalar elastic slack z. Written on exit.
 * @param dual_tol    Convergence tolerance for the dual solve.
 * @param dual_max_iter Maximum dual iterations.
 * @param eta_trial_loc  Accepted latent update eta(lambda*) (device ptr out,
 *                        length n_loc).
 * @param x_trial_loc    Physical view of eta_trial_loc (device ptr out,
 *                        length n_loc): x_trial = bounds.ToPhysical(eta_trial).
 */
void SolveDualEntropy(
    DualSolverKind kind,
    MPI_Comm comm,
    int n_loc, int m, int n_eq,
    bool use_dev,
    const BoundsGeometry& bounds,
    const mfem::real_t* eta_c_loc,
    const mfem::Vector& b0_loc,
    const std::vector<mfem::Vector>& bi_loc,
    const std::vector<double>& F,
    const std::vector<double>& rho,
    const std::vector<double>& a_pen,
    const std::vector<double>& c_pen,
    const std::vector<double>& d_pen,
    std::vector<double>& lam,
    std::vector<double>& mu,
    std::vector<double>& y,
    double& z,
    double dual_tol,
    int dual_max_iter,
    mfem::real_t* eta_trial_loc,
    mfem::real_t* x_trial_loc);

} // namespace detail


// ============================================================
/**
 * @class CCSAOptimizer
 * @brief Serial CCSA optimiser using the Fermi-Dirac Bregman separable
 * approximation, working directly on a latent (logit-type) variable.
 *
 * Solves the same class of problems as MMAOptimizer:
 * @code
 *   min   f0(x)
 *   s.t.  fi(x) <= 0,  i = 1..m
 *         x in the region described by a BoundsGeometry
 * @endcode
 * but Update()/UpdateGCMMA()/KKTresidual() take and return the LATENT
 * variable eta, not the physical x -- see @ref latent in the file header
 * for the full contract and a worked example.
 *
 * @code
 *   auto bounds = mfem_mma::BoundsGeometry::TwoSided(xmin, xmax);
 *   CCSAOptimizer opt(n, m, bounds);
 *   mfem::Vector eta = opt.ToLatent(x0);
 *   for (int k = 0; k < max_iter; ++k) {
 *       mfem::Vector x = opt.ToPhysical(eta);
 *       ComputeObjectiveAndGradients(x, f0, df0, fi, dfi);
 *       opt.Update(eta, df0, f0, fi, dfi.data());
 *       x = opt.ToPhysical(eta);
 *       ComputeObjectiveAndGradients(x, f0, df0, fi, dfi);
 *       if (opt.KKTresidual(eta, df0, f0, fi, dfi.data()) < tol) break;
 *   }
 * @endcode
 *
 * A BoundsGeometry MUST be established (constructor or SetBounds()) before
 * the first Update()/UpdateGCMMA()/KKTresidual() call; these throw
 * std::runtime_error if HasBounds() is false. See @ref dropin in the file
 * header for exactly which parts of the MMAOptimizer/SQOptimizer surface
 * this class does and does not share.
 *
 * @note Not thread-safe (mutable dual state + iteration counter), exactly
 * like MMAOptimizer/SQOptimizer.
 */
// ============================================================
class CCSAOptimizer {
public:
    // ── Constructors ────────────────────────────────────────────────────

    /**
     * @brief Construct with default penalties, bounds deferred.
     * Bounds must be supplied later via SetBounds() before the first
     * Update()/UpdateGCMMA()/KKTresidual() call.
     */
    CCSAOptimizer(int n, int m);

    /** @brief As above, with custom penalty parameters (raw arrays). */
    CCSAOptimizer(int n, int m, const double* a, const double* c, const double* d);

    /** @brief As above, with custom penalty parameters (mfem::Vector). */
    CCSAOptimizer(int n, int m, const mfem::Vector& a, const mfem::Vector& c, const mfem::Vector& d);

    /** @brief Construct with default penalties and an explicit bounds geometry. */
    CCSAOptimizer(int n, int m, const BoundsGeometry& bounds);

    /** @brief As above, with custom penalty parameters (raw arrays). */
    CCSAOptimizer(int n, int m, const BoundsGeometry& bounds,
                  const double* a, const double* c, const double* d);

    /** @brief As above, with custom penalty parameters (mfem::Vector). */
    CCSAOptimizer(int n, int m, const BoundsGeometry& bounds,
                  const mfem::Vector& a, const mfem::Vector& c, const mfem::Vector& d);

    ~CCSAOptimizer() = default;

    // ── Bounds management ────────────────────────────────────────────────

    /**
     * @brief (Re-)set the bounds geometry.
     *
     * Note that changing bounds changes what a given eta value means
     * physically ([Note] Sec. 11 item 2): if you need to preserve a
     * physical point x_phys across a bounds change, convert it yourself,
     * e.g. @code opt.SetBounds(new_bounds); eta = opt.ToLatent(x_phys);
     * @endcode -- the optimiser does not hold an eta of its own to
     * recompute (see @ref latent in the file header).
     */
    void SetBounds(const BoundsGeometry& bounds);

    /// @brief Convenience: TwoSided bounds built directly from xmin/xmax.
    void SetBounds(const mfem::Vector& xmin, const mfem::Vector& xmax);

    bool HasBounds() const { return bounds_.IsSet(); }
    const BoundsGeometry& GetBounds() const { return bounds_; }

    // ── Latent <-> physical conversion (public utility) ──────────────────
    // The primary way to move between the physical design and the latent
    // variable eta that Update()/UpdateGCMMA()/KKTresidual() operate on.

    /// @brief Physical -> latent, using this optimiser's current bounds geometry.
    mfem::Vector ToLatent(const mfem::Vector& x) const { return bounds_.ToLatent(x); }
    void ToLatent(const mfem::Vector& x, mfem::Vector& eta) const { bounds_.ToLatent(x,eta); }

    /// @brief Latent -> physical, using this optimiser's current bounds geometry.
    mfem::Vector ToPhysical(const mfem::Vector& eta) const { return bounds_.ToPhysical(eta); }
    void ToPhysical(const mfem::Vector& eta, mfem::Vector& x) const { bounds_.ToPhysical(eta,x); }

    // ── Dual solver selection ────────────────────────────────────────────

    /**
     * @brief Select the dual-solve strategy.  Default: ProjectedAscent
     * (the simple, non-globally-convergent solver -- see @ref why above).
     */
    void SetDualSolver(DualSolverKind kind) { dual_solver_ = kind; }
    DualSolverKind GetDualSolver() const { return dual_solver_; }

    void SetDualTolerance(double tol) { dual_tol_ = tol; }
    void SetDualMaxIterations(int n)  { dual_max_iter_ = n; }

    // ── Conservatism (rho) controls ──────────────────────────────────────

    /**
     * @brief Configure the rho (conservatism) update rule used by
     * UpdateGCMMA() ([Note] Sec. 5.1, eq. 36-37).
     *
     * @param rho_min    Floor applied to every rho_i, every outer iteration.
     * @param gamma_safe Safety factor (>1) multiplying the exact
     *                    conservatism-restoring increase, eq. 36. Default 1.1.
     * @param gamma_max  Maximum per-inner-iteration growth factor, eq. 36.
     *                    Default 10.
     * @param theta_decrease  Between-outer-iteration decay in (0,1], eq. 37.
     *                    Default 1 (no decay).
     */
    void SetRhoParams(double rho_min, double gamma_safe = 1.1,
                       double gamma_max = 10.0, double theta_decrease = 1.0);

    // ── Equality-constraint factories (use PackFival()/PackedDfidx from MMA_MFEM.hpp) ─

    static CCSAOptimizer WithEqualities(int n, int n_ineq, int n_eq);
    static CCSAOptimizer WithEqualities(int n, int n_ineq, int n_eq,
                                        const BoundsGeometry& bounds);
    static CCSAOptimizer WithRelaxedEqualities(int n, int n_ineq, int n_eq);
    static CCSAOptimizer WithRelaxedEqualities(int n, int n_ineq, int n_eq,
                                               const BoundsGeometry& bounds);

    // ── Outer iteration ───────────────────────────────────────────────────

    /**
     * @brief Perform one plain (non-globally-convergent) CCSA outer step.
     *
     * Internally: builds C_j(lambda)/R(lambda) on the device from the
     * latent center @p x, solves the dual sub-problem via the selected
     * DualSolverKind, and accepts the resulting eta_trial unconditionally
     * (no conservatism check -- see UpdateGCMMA() for that).
     *
     * @param[in,out] x     Latent variable eta, NOT the physical design --
     *                      see @ref latent in the file header. Overwritten
     *                      with the new eta on exit.
     * @param[in]  df0dx    Objective gradient in PHYSICAL space, df0/dx,
     *                      evaluated at ToPhysical(x) (i.e. at the physical
     *                      point corresponding to @p x on entry).
     * @param[in]  f0val    Objective value f0(ToPhysical(x)). Accepted but
     *                      only used as F[0] for GCMMA-style bookkeeping
     *                      elsewhere; plain Update() does not need it for
     *                      the sub-problem itself.
     * @param[in]  fival    Constraint values, length m (see PackFival() for
     *                      the equality-constraint layout).
     * @param[in]  dfidx    Constraint gradients in PHYSICAL space (array of
     *                      m Vectors); nullptr when m == 0.
     *
     * @throws std::runtime_error if HasBounds() is false.
     */
    void Update(mfem::Vector& x,
                const mfem::Vector& df0dx,
                mfem::real_t f0val,
                const mfem::Vector& fival,
                const mfem::Vector* dfidx);

    /**
     * @brief Perform one globally-convergent CCSA ("GCMMA-style") outer step.
     *
     * Single-inner-iteration variant: rho is (re-)estimated from the
     * current gradient magnitudes and one sub-problem is solved.
     * Re-computing rho from fresh gradients every call provides the same
     * implicit conservatism adaptation MMAOptimizer relies on.
     *
     * The rho estimate is computed by the protected virtual
     * ComputeInitialRho_() -- see that method's doc comment for the planned
     * SiMPL/Barzilai-Borwein extension point. Same @p x / df0dx / dfidx
     * contract as Update() above (latent in/out, physical-space gradients).
     */
    void UpdateGCMMA(mfem::Vector& x,
                     const mfem::Vector& df0dx,
                     mfem::real_t f0val,
                     const mfem::Vector& fival,
                     const mfem::Vector* dfidx,
                     int* innerIter = nullptr);

    /**
     * @brief GCMMA with full inner conservatism loop and user-supplied
     * function evaluator, mirroring MMAOptimizer's corresponding overload
     * (same EvalCallback contract: called with a PHYSICAL trial point,
     * since that is what the user's evaluator needs).
     *
     * After solving the sub-problem for a candidate latent update, @p
     * eval_fi is called at ToPhysical(eta_trial) to get the true function
     * values. If the entropy model under-estimates any of them ([Note]
     * eq. 32-33), rho is increased (eq. 36) and the sub-problem is
     * re-solved, up to @p max_inner times. Same @p x / df0dx / dfidx
     * contract as Update() above (latent in/out, physical-space gradients).
     */
    void UpdateGCMMA(mfem::Vector& x,
                     const mfem::Vector& df0dx,
                     mfem::real_t f0val,
                     const mfem::Vector& fival,
                     const mfem::Vector* dfidx,
                     GCMMAEvalCallback eval_fi,
                     int max_inner = 15,
                     int* innerIter = nullptr);

    // ── Convergence ───────────────────────────────────────────────────────

    /**
     * @brief Latent-space KKT/stationarity residual.
     *
     * Unlike MMAOptimizer::KKTresidual() (a physical-space PROJECTED
     * gradient norm), this is a plain chain-rule stationarity check in
     * eta-space: dL/deta_j = (dL/dx_j) * (dx_j/deta_j), with no projection
     * needed since eta is unconstrained -- see @ref latent in the file
     * header for why. Same normalisation convention as MMAOptimizer
     * otherwise (mean-square Lagrangian-gradient term plus
     * complementary-slackness terms for the constraints).
     *
     * @param x       Latent variable eta (same point Update() was just
     *                called with/returned).
     * @param df0dx,fival,dfidx  Physical-space gradients/values at
     *                ToPhysical(x), same as Update().
     */
    mfem::real_t KKTresidual(const mfem::Vector& x,
                             const mfem::Vector& df0dx,
                             mfem::real_t f0val,
                             const mfem::Vector& fival,
                             const mfem::Vector* dfidx,
                             double* lambda_out = nullptr) const;

    // ── Accessors ─────────────────────────────────────────────────────────

    int GetIteration()  const { return iter_; }
    int NumIterations() const { return iter_; }
    const std::vector<double>& GetLambda() const { return lam_; }

    int NumEqualities()   const { return n_eq_; }
    int NumInequalities() const { return m_ - 2*n_eq_; }
    int NumConstraints()  const { return m_ - n_eq_; }

    // ── Unconstrained convenience overloads (m=0) ────────────────────────

    void Update(mfem::Vector& x, const mfem::Vector& df0dx, mfem::real_t f0val)
    { static const mfem::Vector e; Update(x,df0dx,f0val,e,nullptr); }

    void UpdateGCMMA(mfem::Vector& x, const mfem::Vector& df0dx, mfem::real_t f0val,
                     int* innerIter = nullptr)
    { static const mfem::Vector e; UpdateGCMMA(x,df0dx,f0val,e,nullptr,innerIter); }

    mfem::real_t KKTresidual(const mfem::Vector& x, const mfem::Vector& df0dx,
                              mfem::real_t f0val) const
    { static const mfem::Vector e; return KKTresidual(x,df0dx,f0val,e,nullptr); }

protected:
    /**
     * @brief Compute the initial per-model conservatism weights rho used at
     * the start of each UpdateGCMMA() call, before any conservatism-driven
     * increase.
     *
     * Default implementation: the same gradient-magnitude heuristic used by
     * MMAOptimizer::UpdateGCMMA() (rho_i = max(rho_min, 0.5/n * sum_j
     * |dfi/dxj| * scale_j)), which is what the project currently asks for
     * ("use the same approach as the globally convergent MMA for now").
     * Unlike MMA, @p scale_j here is GetBounds().Scale() (h_j: u-ell for
     * TwoSided, the user scale for one-sided).
     *
     * @par Future extension (SiMPL-style BB step control)
     * The Barzilai-Borwein step size of Kim, Lazarov, Surowiec & Keith
     * (2025), "SiMPL", estimates a step size from two consecutive latent
     * iterates and gradients:
     * @f[
     *   \alpha_{k,BB} = \frac{(\eta_k-\eta_{k-1})^\top M (\eta_k-\eta_{k-1})}
     *                        {|(g_k-g_{k-1})^\top M (\eta_k-\eta_{k-1})|}
     * @f]
     * with M the (diagonal) mirror-map metric. In this rho-based
     * formulation the analogous quantity is R(lambda) = rho_0 + sum lambda_i
     * rho_i, which plays the role of an inverse step size in the closed-form
     * latent update (eq. 91/98 in [Note]). A future override of this method
     * can therefore replace the fixed-formula rho_0 by 1/alpha_{k,BB},
     * computed from the eta_prev_/df0dx_prev_ history already tracked by
     * this base class (see below) -- no other part of the optimiser needs
     * to change. This override point is provided now so that experiment can
     * be dropped in later without touching Update()/UpdateGCMMA().
     *
     * @param df0dx,dfidx  Same arguments UpdateGCMMA() received.
     * @param[out] rho_out  Length m+1; rho_out[0] is for the objective,
     *                      rho_out[i+1] for constraint i.
     */
    virtual void ComputeInitialRho_(const mfem::Vector& df0dx,
                                     const mfem::Vector* dfidx,
                                     std::vector<double>& rho_out) const;

private:
    CCSAOptimizer(int n, int m,
                  const BoundsGeometry* bounds,
                  const double* a, const double* c, const double* d);

    /// @brief Throws std::runtime_error if HasBounds() is false. Called at
    /// the top of Update()/UpdateGCMMA()/KKTresidual(): a BoundsGeometry
    /// must be established via a constructor or SetBounds() beforehand --
    /// there is no more auto-detection from xmin/xmax (see @ref latent).
    void RequireBounds_() const;
    void DecayRho_();

    int n_, m_, iter_ = 0, n_eq_ = 0;
    BoundsGeometry bounds_;

    mfem::Vector eta_prev_;        ///< previous latent state (future BB hook)
    mfem::Vector df0dx_prev_;      ///< previous objective gradient (future BB hook)
    bool have_prev_ = false;

    std::vector<double> a_, c_, d_;                 ///< penalty parameters, length m_
    std::vector<double> lam_, mu_, y_;               ///< dual state, length m_
    double z_ = 0.0;
    std::vector<double> rho_;                        ///< length m_+1
    bool have_rho_ = false;   ///< true once rho_ has been seeded by
                              ///< ComputeInitialRho_(); after that, rho_
                              ///< persists across calls (grown by the
                              ///< callback conservatism loop, decayed by
                              ///< DecayRho_()) rather than being
                              ///< re-derived from scratch every call.

    double rho_min_ = 1e-6, rho_safe_ = 1.1, rho_max_growth_ = 10.0, theta_rho_ = 1.0;
    DualSolverKind dual_solver_ = DualSolverKind::ProjectedAscent;
    double dual_tol_ = 1e-9;
    int dual_max_iter_ = 200;
};


#ifdef MFEM_USE_MPI
// ============================================================
/**
 * @class CCSAOptimizerParallel
 * @brief MPI-parallel counterpart of CCSAOptimizer, one local mfem::Vector
 * chunk per rank -- mirrors MMAOptimizerParallel's distribution model.
 *
 * All local design-variable Vectors (x, df0dx, dfidx, eta, the
 * BoundsGeometry's lo/hi/scale) hold only this rank's n_local entries.
 * f0val and fival must be globally consistent (same value on every rank)
 * before each call, exactly as for MMAOptimizerParallel.  The scalar dual
 * state (lambda, mu, y, z, rho) is replicated and solved identically on
 * every rank via MPI_Allreduce, exactly mirroring detail::SolveDualIP's
 * strategy for MMA.
 */
// ============================================================
class CCSAOptimizerParallel {
public:
    CCSAOptimizerParallel(MPI_Comm comm, int n_local, int m);
    CCSAOptimizerParallel(MPI_Comm comm, int n_local, int m,
                          const double* a, const double* c, const double* d);
    CCSAOptimizerParallel(MPI_Comm comm, int n_local, int m,
                          const mfem::Vector& a, const mfem::Vector& c, const mfem::Vector& d);
    CCSAOptimizerParallel(MPI_Comm comm, int n_local, int m,
                          const BoundsGeometry& bounds_local);
    CCSAOptimizerParallel(MPI_Comm comm, int n_local, int m,
                          const BoundsGeometry& bounds_local,
                          const double* a, const double* c, const double* d);
    CCSAOptimizerParallel(MPI_Comm comm, int n_local, int m,
                          const BoundsGeometry& bounds_local,
                          const mfem::Vector& a, const mfem::Vector& c, const mfem::Vector& d);

    ~CCSAOptimizerParallel() = default;

    // ── Bounds management (bounds_local describes THIS rank's chunk) ────
    // See CCSAOptimizer::SetBounds(); identical semantics.
    void SetBounds(const BoundsGeometry& bounds_local);
    void SetBounds(const mfem::Vector& xmin_local, const mfem::Vector& xmax_local);

    bool HasBounds() const { return bounds_.IsSet(); }
    const BoundsGeometry& GetBounds() const { return bounds_; }

    // ── Latent <-> physical (local chunk) ────────────────────────────────
    // The primary way to move between the physical design and the latent
    // variable eta that Update()/UpdateGCMMA()/KKTresidual() operate on.
    mfem::Vector ToLatent(const mfem::Vector& x_local) const { return bounds_.ToLatent(x_local); }
    void ToLatent(const mfem::Vector& x_local, mfem::Vector& eta_local) const
    { bounds_.ToLatent(x_local, eta_local); }
    mfem::Vector ToPhysical(const mfem::Vector& eta_local) const { return bounds_.ToPhysical(eta_local); }
    void ToPhysical(const mfem::Vector& eta_local, mfem::Vector& x_local) const
    { bounds_.ToPhysical(eta_local, x_local); }

    // ── Dual solver / rho controls (identical semantics to serial class) ─
    void SetDualSolver(DualSolverKind kind) { dual_solver_ = kind; }
    DualSolverKind GetDualSolver() const { return dual_solver_; }
    void SetDualTolerance(double tol) { dual_tol_ = tol; }
    void SetDualMaxIterations(int n)  { dual_max_iter_ = n; }
    void SetRhoParams(double rho_min, double gamma_safe = 1.1,
                       double gamma_max = 10.0, double theta_decrease = 1.0);

    // ── Equality-constraint factories ────────────────────────────────────
    static CCSAOptimizerParallel WithEqualities(MPI_Comm comm, int n_local,
                                                int n_ineq, int n_eq);
    static CCSAOptimizerParallel WithEqualities(MPI_Comm comm, int n_local,
                                                int n_ineq, int n_eq,
                                                const BoundsGeometry& bounds_local);
    static CCSAOptimizerParallel WithRelaxedEqualities(MPI_Comm comm, int n_local,
                                                       int n_ineq, int n_eq);
    static CCSAOptimizerParallel WithRelaxedEqualities(MPI_Comm comm, int n_local,
                                                       int n_ineq, int n_eq,
                                                       const BoundsGeometry& bounds_local);

    // ── Outer iteration (collective; all ranks call together) ───────────
    // See CCSAOptimizer::Update()/UpdateGCMMA(); identical contract, with
    // x_local/df0dx_local/dfidx_local holding this rank's chunk only.
    void Update(mfem::Vector& x_local,
                const mfem::Vector& df0dx_local,
                mfem::real_t f0val,
                const mfem::Vector& fival,
                const mfem::Vector* dfidx_local);

    void UpdateGCMMA(mfem::Vector& x_local,
                     const mfem::Vector& df0dx_local,
                     mfem::real_t f0val,
                     const mfem::Vector& fival,
                     const mfem::Vector* dfidx_local,
                     int* innerIter = nullptr);

    void UpdateGCMMA(mfem::Vector& x_local,
                     const mfem::Vector& df0dx_local,
                     mfem::real_t f0val,
                     const mfem::Vector& fival,
                     const mfem::Vector* dfidx_local,
                     GCMMAEvalCallback eval_fi,
                     int max_inner = 15,
                     int* innerIter = nullptr);

    /// @brief See CCSAOptimizer::KKTresidual(); identical latent-space
    /// stationarity formula, with the primal term globally reduced across
    /// ranks and normalised by n_global_.
    mfem::real_t KKTresidual(const mfem::Vector& x_local,
                              const mfem::Vector& df0dx_local,
                              mfem::real_t f0val,
                              const mfem::Vector& fival,
                              const mfem::Vector* dfidx_local,
                              double* lambda_out = nullptr) const;

    int GetIteration()  const { return iter_; }
    int NumIterations() const { return iter_; }
    const std::vector<double>& GetLambda() const { return lam_; }
    int NumEqualities()   const { return n_eq_; }
    int NumInequalities() const { return m_ - 2*n_eq_; }
    int NumConstraints()  const { return m_ - n_eq_; }

    void Update(mfem::Vector& x, const mfem::Vector& df0dx, mfem::real_t f0val)
    { static const mfem::Vector e; Update(x,df0dx,f0val,e,nullptr); }

    void UpdateGCMMA(mfem::Vector& x, const mfem::Vector& df0dx, mfem::real_t f0val,
                     int* innerIter = nullptr)
    { static const mfem::Vector e; UpdateGCMMA(x,df0dx,f0val,e,nullptr,innerIter); }

    mfem::real_t KKTresidual(const mfem::Vector& x, const mfem::Vector& df0dx,
                              mfem::real_t f0val) const
    { static const mfem::Vector e; return KKTresidual(x,df0dx,f0val,e,nullptr); }

protected:
    /// @brief See CCSAOptimizer::ComputeInitialRho_(); identical role/contract,
    /// evaluated with globally-reduced gradient sums.
    virtual void ComputeInitialRho_(const mfem::Vector& df0dx_local,
                                     const mfem::Vector* dfidx_local,
                                     std::vector<double>& rho_out) const;

private:
    CCSAOptimizerParallel(MPI_Comm comm, int n_local, int m,
                          const BoundsGeometry* bounds_local,
                          const double* a, const double* c, const double* d);

    /// @brief See CCSAOptimizer::RequireBounds_(); identical role.
    void RequireBounds_() const;
    void DecayRho_();

    MPI_Comm comm_;
    int n_local_, m_, iter_ = 0, n_eq_ = 0;
    long long n_global_ = 0;
    BoundsGeometry bounds_;

    mfem::Vector eta_prev_, df0dx_prev_;
    bool have_prev_ = false;

    std::vector<double> a_, c_, d_;
    std::vector<double> lam_, mu_, y_;
    double z_ = 0.0;
    std::vector<double> rho_;
    bool have_rho_ = false;   ///< see CCSAOptimizer::have_rho_

    double rho_min_ = 1e-6, rho_safe_ = 1.1, rho_max_growth_ = 10.0, theta_rho_ = 1.0;
    DualSolverKind dual_solver_ = DualSolverKind::ProjectedAscent;
    double dual_tol_ = 1e-9;
    int dual_max_iter_ = 200;
};
#endif // MFEM_USE_MPI

} // namespace mfem_mma
