# Copyright (c) 2010-2025, Lawrence Livermore National Security, LLC. Produced
# at the Lawrence Livermore National Laboratory. All Rights reserved. See files
# LICENSE and NOTICE for details. LLNL-CODE-806117.
#
# This file is part of the MFEM library. For more information and source code
# availability visit https://mfem.org.
#
# MFEM is free software; you can redistribute it and/or modify it under the
# terms of the BSD-3 license. We welcome feedback and contributions, see file
# CONTRIBUTING.md for details.
---
name: build-file-lsan
on:
  workflow_call:
jobs:
  build-file-lsan:
    runs-on: ubuntu-latest
    name: lsan.supp
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sanitize/config
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{env.LSAN_DIR}}
          key: build-lsan-suppression-file
      - name: Setup
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{env.LSAN_DIR}}
          cat << EOF > ${{env.LSAN_DIR}}/${{env.LSAN_FILE}}
          leak:libevent_core-2.1.so
          leak:ompi_mpi_finalize
          leak:ompi_mpi_init
          leak:PMPI_Init
          leak:strdup
          EOF
