#!/bin/bash

. tests/scripts/history_checks.bash

# # If in travis context we need to checkout a branch, otherwise travis works in detached head.
# if ! git checkout -b travis_tests
# then
#     err "failed to create a branch"
#     exit 1
# fi

####
msg "Check presence of binary files in branch history."
branch_res=0

if ! check_branch # Read: "if check fails"
then
    err "ERROR: something went wrong in branch checks"
    branch_check=1
fi

####
msg "Check code style."
style_res=0

if ! make style-check
then
    err "ERROR: something went wrong during style check"
    style_check=1
fi

####
exit ${branch_check} || ${style_check}

# Utilities

function msg()
{
    echo "travis_tests: $*"
}

function err()
{
    msg $* 1>&2
}

