#!/bin/bash

. tests/scripts/history_checks.bash

####
# If in travis context we need to checkout a branch, otherwise travis works in detached head.
if ! git checkout -b travis_tests
then
    err "failed to create a branch"
    exit 1
fi

####
msg "Check presence of binary files in branch history."

# Read: "if check_bin_in_branch fails"
if ! check_branch
then
    err "ERROR: something went wrong in branch checks"
    exit 1
fi

function msg() {
    echo "travis_tests: $*"
}

function err() {
    echo "travis_tests: $*" 1>&2
}
####
# TODO: Code style checks
